/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Operator Me
         * @description Who the plane admitted and what the entry grants; the check a skill
         *     makes before its first read.
         */
        get: operations["operator_me_v1_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orgs */
        get: operations["list_orgs_v1_admin_orgs_get"];
        put?: never;
        /** Create Org */
        post: operations["create_org_v1_admin_orgs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orgs/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Org */
        get: operations["get_org_v1_admin_orgs__org_id__get"];
        put?: never;
        post?: never;
        /** Delete Org */
        delete: operations["delete_org_v1_admin_orgs__org_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orgs/{org_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_v1_admin_orgs__org_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orgs/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_v1_admin_orgs__org_id__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_v1_admin_orgs__org_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orgs/{org_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_v1_admin_orgs__org_id__tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/size": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform Size */
        get: operations["platform_size_v1_admin_size_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Api Keys */
        get: operations["list_api_keys_v1_api_keys_get"];
        put?: never;
        /** Create Api Key */
        post: operations["create_api_key_v1_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys/{api_key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Api Key */
        delete: operations["revoke_api_key_v1_api_keys__api_key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange Session */
        post: operations["exchange_session_v1_auth_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_v1_me_patch"];
        trace?: never;
    };
    "/v1/me/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Identity */
        get: operations["my_identity_v1_me_identity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memberships */
        get: operations["list_memberships_v1_memberships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memberships/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_v1_memberships__user_id__delete"];
        options?: never;
        head?: never;
        /** Update Membership */
        patch: operations["update_membership_v1_memberships__user_id__patch"];
        trace?: never;
    };
    "/v1/orgs/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Org */
        get: operations["current_org_v1_orgs_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/realtime/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mint Ticket */
        post: operations["mint_ticket_v1_realtime_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_v1_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Session */
        delete: operations["revoke_session_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_v1_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        /** Delete Task */
        delete: operations["delete_task_v1_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_v1_tasks__task_id__patch"];
        trace?: never;
    };
    "/v1/tasks/{task_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move Task */
        post: operations["move_task_v1_tasks__task_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddApiKeyRequest */
        AddApiKeyRequest: {
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
            /** Ttl Days */
            ttl_days?: number | null;
        };
        /**
         * AddMemberRequest
         * @description A person in the org, as `add-member` seeds one; the owner and the
         *     service role are refused, since the one owner is the one the create
         *     minted.
         */
        AddMemberRequest: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            role: components["schemas"]["Role"];
        };
        /** AddTaskRequest */
        AddTaskRequest: {
            /** Assignee Id */
            assignee_id?: string | null;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Title */
            title: string;
        };
        /**
         * ApiKeyPageView
         * @description One page of the api key list, newest first; `next_cursor` as on
         *     `UserPageView`.
         */
        ApiKeyPageView: {
            /** Items */
            items: components["schemas"]["ApiKeyView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ApiKeyView */
        ApiKeyView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * CreateOrgRequest
         * @description An org with its owner, as `bootstrap` seeds one. The owner's identity
         *     is created with the password, or kept with its own when the email is
         *     known already.
         */
        CreateOrgRequest: {
            /** Name */
            name: string;
            /** Owner Email */
            owner_email: string;
            /** Owner Name */
            owner_name: string;
            /** Owner Password */
            owner_password: string;
            /** Slug */
            slug: string;
        };
        /**
         * CredentialKind
         * @enum {string}
         */
        CredentialKind: "api_key" | "session_token" | "login" | "socket_ticket" | "internal";
        /**
         * EventView
         * @description One record of the tenant's append-only stream, paged by `after_seq`.
         *     `kind` is "<namespace>.<entity>.<action>", or an audit kind; the payload
         *     stays inside, an event is a record and not a second read path. The rename
         *     from `entity`/`entity_id`/`action` stayed under `/v1` (ADR 0006).
         */
        EventView: {
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /** Kind */
            kind: string;
            /**
             * Produced At
             * Format: date-time
             */
            produced_at: string;
            /** Seq */
            seq: number;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
        };
        /** ExchangeSessionRequest */
        ExchangeSessionRequest: {
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdentityView
         * @description The person behind the caller's user; never carries the password hash.
         *     `operator_role` is the allowlist entry: null for a person who is not an
         *     operator.
         */
        IdentityView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            operator_role: components["schemas"]["OperatorRole"] | null;
        };
        /**
         * IssuedApiKeyView
         * @description The key in the clear is present on the first response only: the stored
         *     outcome of the create carries no secret, so a replay under the same
         *     Idempotency-Key answers with `key` null and `Idempotent-Replayed: true`. A
         *     client that lost the first response revokes the key and issues another.
         */
        IssuedApiKeyView: {
            api_key: components["schemas"]["ApiKeyView"];
            /** Key */
            key: string | null;
        };
        /**
         * IssuedLoginView
         * @description Carries the freshly minted login credential in the clear, once.
         */
        IssuedLoginView: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Memberships */
            memberships: components["schemas"]["MembershipChoiceView"][];
            /** Token */
            token: string;
        };
        /** IssuedSessionView */
        IssuedSessionView: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            org: components["schemas"]["OrgView"];
            role: components["schemas"]["Role"];
            /** Token */
            token: string;
            user: components["schemas"]["UserView"];
        };
        /**
         * IssuedTicketView
         * @description Carries the freshly minted socket ticket in the clear, once; redeeming
         *     it opens the channel and re-checks the credential behind it.
         */
        IssuedTicketView: {
            /** Expires In Seconds */
            expires_in_seconds: number;
            /** Ticket */
            ticket: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeView */
        MeView: {
            /** App */
            app: string;
            org: components["schemas"]["OrgView"];
            /** Permissions */
            permissions: components["schemas"]["Permission"][];
            role: components["schemas"]["Role"];
            user: components["schemas"]["UserView"];
        };
        /** MembershipChoiceView */
        MembershipChoiceView: {
            org: components["schemas"]["OrgView"];
            role: components["schemas"]["Role"];
            user: components["schemas"]["UserView"];
        };
        /** MembershipView */
        MembershipView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["Role"];
            /** Teams */
            teams: string[];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * MoveTaskRequest
         * @description Places an open task right after `after_id`; null puts it at the top.
         *     `version` is the moved task's, as on `UpdateTaskRequest`.
         */
        MoveTaskRequest: {
            /** After Id */
            after_id?: string | null;
            /** Version */
            version: number;
        };
        /**
         * OperatorEventView
         * @description The same record as an operator reads it, with the two provenance fields
         *     a tenant's own feed leaves out: the request that produced it and the app
         *     it came from, which is what a support investigation correlates on.
         */
        OperatorEventView: {
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /** App */
            app: string;
            /** Kind */
            kind: string;
            /**
             * Produced At
             * Format: date-time
             */
            produced_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Seq */
            seq: number;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
        };
        /**
         * OperatorRole
         * @description What an allowlist entry lets an operator do across every tenant. Write
         *     includes read; the tenancy namespace's table says which permissions each
         *     role holds, as it does for `Role`.
         * @enum {string}
         */
        OperatorRole: "read" | "write";
        /**
         * OperatorView
         * @description Who the operator plane admitted: the identity and what its allowlist
         *     entry grants, so a skill checks it holds the entry it expects before it
         *     reads anything.
         */
        OperatorView: {
            /** Email */
            email: string;
            /**
             * Identity Id
             * Format: uuid
             */
            identity_id: string;
            operator_role: components["schemas"]["OperatorRole"];
        };
        /** OrgView */
        OrgView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * Permission
         * @enum {string}
         */
        Permission: "read" | "write" | "manage_members" | "manage_keys";
        /**
         * PlatformSizeView
         * @description How big the platform is, what the first responder to an alarm reads
         *     before it escalates: live tenants and users, and the tasks created and
         *     events produced in the last twenty-four hours, a window that starts at
         *     `since` and ends at the read.
         */
        PlatformSizeView: {
            /** Events Last 24H */
            events_last_24h: number;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /** Tasks Last 24H */
            tasks_last_24h: number;
            /** Tenants */
            tenants: number;
            /** Users */
            users: number;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "owner" | "admin" | "member" | "viewer" | "service";
        /**
         * SessionView
         * @description Only the hash of a token is ever kept, so a session view carries no secret.
         */
        SessionView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            credential_kind: components["schemas"]["CredentialKind"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revoked At */
            revoked_at: string | null;
        };
        /**
         * TaskPageView
         * @description One page of a task list. `next_cursor` fetches the next page of the same
         *     list, open or done, and is null on the last page. The page size is
         *     clamped, and a list the clamp cut still says a page follows.
         */
        TaskPageView: {
            /** Items */
            items: components["schemas"]["TaskView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * TaskScope
         * @description Which tasks a list shows. The org is the team.
         * @enum {string}
         */
        TaskScope: "mine" | "team";
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "open" | "done";
        /** TaskView */
        TaskView: {
            /** Assignee Id */
            assignee_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes: string;
            /** Position */
            position: number;
            status: components["schemas"]["TaskStatus"];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** UpdateMeRequest */
        UpdateMeRequest: {
            /** Display Name */
            display_name: string;
        };
        /** UpdateMembershipRequest */
        UpdateMembershipRequest: {
            role: components["schemas"]["Role"];
        };
        /**
         * UpdateTaskRequest
         * @description A partial update: absent fields are kept. An explicit null
         *     `assignee_id` unassigns the task. `version` is the task's version as the
         *     caller read it: the update lands only when the task is still at it, and
         *     is refused with 409 `version_mismatch` when another write landed since,
         *     so the caller reads again and decides over the current task.
         */
        UpdateTaskRequest: {
            /** Assignee Id */
            assignee_id?: string | null;
            /** Notes */
            notes?: string | null;
            status?: components["schemas"]["TaskStatus"] | null;
            /** Title */
            title?: string | null;
            /** Version */
            version: number;
        };
        /**
         * UserPageView
         * @description One page of the tenant's members. `next_cursor` fetches the next page
         *     and is null on the last one, so a client reads every member instead of
         *     whatever a fixed limit happened to cover.
         */
        UserPageView: {
            /** Items */
            items: components["schemas"]["UserView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** UserView */
        UserView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    operator_me_v1_admin_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orgs_v1_admin_orgs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_org_v1_admin_orgs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_org_v1_admin_orgs__org_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_org_v1_admin_orgs__org_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_v1_admin_orgs__org_id__events_get: {
        parameters: {
            query?: {
                after_seq?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorEventView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_v1_admin_orgs__org_id__members_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_v1_admin_orgs__org_id__members_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
                "idempotency-key"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_v1_admin_orgs__org_id__tasks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"];
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    platform_size_v1_admin_size_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformSizeView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_v1_api_keys_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyPageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_key_v1_api_keys_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddApiKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedApiKeyView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_v1_api_keys__api_key_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                api_key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: {
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedLoginView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exchange_session_v1_auth_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedSessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_v1_events_get: {
        parameters: {
            query?: {
                after_seq?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_v1_me_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_identity_v1_me_identity_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memberships_v1_memberships_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_v1_memberships__user_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_membership_v1_memberships__user_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMembershipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_org_v1_orgs_current_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mint_ticket_v1_realtime_tickets_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedTicketView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_v1_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_session_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_v1_tasks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"];
                scope?: components["schemas"]["TaskScope"];
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_v1_tasks__task_id__delete: {
        parameters: {
            query: {
                /** @description The task's version as the caller read it; 409 `version_mismatch` when the task changed since. */
                version: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_v1_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_task_v1_tasks__task_id__move_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_v1_users_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
