/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Operator Me
         * @description Who the plane admitted and what the entry grants; the check a skill
         *     makes before its first read.
         */
        get: operations["operator_me_v1_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/me/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint Token
         * @description An operator token for an agent: one permission, never wider than the
         *     caller's entry, an hour at most. Minted only from a sign-in that
         *     verified a second factor, so a token never mints a token.
         */
        post: operations["mint_token_v1_admin_me_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/me/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enrol Totp
         * @description Mints the operator's TOTP secret and answers it once, as the
         *     `otpauth://` URI an authenticator app reads. It creates no row, and a
         *     retry is safe: minting again replaces a secret that was never confirmed,
         *     so it takes no Idempotency-Key. Refused once one is confirmed.
         */
        post: operations["enrol_totp_v1_admin_me_totp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/me/totp/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Totp
         * @description The first code confirms the secret. From then on the plane admits
         *     this identity only on a sign-in that verified a code.
         */
        post: operations["confirm_totp_v1_admin_me_totp_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orgs */
        get: operations["list_orgs_v1_admin_orgs_get"];
        put?: never;
        /** Create Org */
        post: operations["create_org_v1_admin_orgs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orgs/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Org */
        get: operations["get_org_v1_admin_orgs__org_id__get"];
        put?: never;
        post?: never;
        /** Delete Org */
        delete: operations["delete_org_v1_admin_orgs__org_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orgs/{org_id}/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Org Billing */
        get: operations["get_org_billing_v1_admin_orgs__org_id__billing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orgs/{org_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_v1_admin_orgs__org_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orgs/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_v1_admin_orgs__org_id__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_v1_admin_orgs__org_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orgs/{org_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Comp Plan
         * @description Grants the org a plan with no payment, or takes the grant back. A put:
         *     the same body twice leaves the same grant.
         */
        put: operations["comp_plan_v1_admin_orgs__org_id__plan_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orgs/{org_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_v1_admin_orgs__org_id__tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/password-resets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Sets a person's password, the recovery a platform with no verified
         *     mailbox has; a write operator signed in with a second factor, audited.
         */
        post: operations["reset_password_v1_admin_password_resets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/size": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform Size */
        get: operations["platform_size_v1_admin_size_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Api Keys */
        get: operations["list_api_keys_v1_api_keys_get"];
        put?: never;
        /** Create Api Key */
        post: operations["create_api_key_v1_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys/{api_key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Api Key */
        delete: operations["revoke_api_key_v1_api_keys__api_key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Memberships */
        get: operations["list_my_memberships_v1_auth_memberships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange Session */
        post: operations["exchange_session_v1_auth_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Up */
        post: operations["sign_up_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Billing */
        get: operations["get_billing_v1_billing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel
         * @description The paid plan ends at its period's end; the org keeps it until then.
         */
        post: operations["cancel_v1_billing_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Checkout
         * @description Makes the org's customer at the processor the first time, which is a
         *     durable row, so the route runs under the idempotency record.
         */
        post: operations["start_checkout_v1_billing_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Portal */
        post: operations["open_portal_v1_billing_portal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_v1_billing_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_v1_me_patch"];
        trace?: never;
    };
    "/v1/me/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Identity */
        get: operations["my_identity_v1_me_identity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memberships */
        get: operations["list_memberships_v1_memberships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memberships/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_v1_memberships__user_id__delete"];
        options?: never;
        head?: never;
        /** Update Membership */
        patch: operations["update_membership_v1_memberships__user_id__patch"];
        trace?: never;
    };
    "/v1/orgs/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Org */
        get: operations["current_org_v1_orgs_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/realtime/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mint Ticket */
        post: operations["mint_ticket_v1_realtime_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_v1_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Session */
        delete: operations["revoke_session_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_v1_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        /** Delete Task */
        delete: operations["delete_task_v1_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_v1_tasks__task_id__patch"];
        trace?: never;
    };
    "/v1/tasks/{task_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move Task */
        post: operations["move_task_v1_tasks__task_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe Delivery */
        post: operations["stripe_delivery_webhooks_stripe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddApiKeyRequest */
        AddApiKeyRequest: {
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
            /** Ttl Days */
            ttl_days?: number | null;
        };
        /**
         * AddMemberRequest
         * @description A person in the org, as `add-member` seeds one; the owner and the
         *     service role are refused, since the one owner is the one the create
         *     minted.
         */
        AddMemberRequest: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            role: components["schemas"]["Role"];
        };
        /** AddTaskRequest */
        AddTaskRequest: {
            /** Assignee Id */
            assignee_id?: string | null;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Title */
            title: string;
        };
        /**
         * ApiKeyPageView
         * @description One page of the api key list, newest first; `next_cursor` as on
         *     `UserPageView`.
         */
        ApiKeyPageView: {
            /** Items */
            items: components["schemas"]["ApiKeyView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ApiKeyView */
        ApiKeyView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * BillingView
         * @description The org's plan now, where it comes from, and what the org uses of it.
         *     `ends_at` is set when a paid plan is set to end; the org is on
         *     `plan_after` from then, and keeps everything it has. `can_manage` says
         *     whether the caller may change the plan: an owner or an admin.
         */
        BillingView: {
            /** Active Tasks */
            active_tasks: number;
            /** Can Manage */
            can_manage: boolean;
            /** Cancel At Period End */
            cancel_at_period_end: boolean;
            comped_plan: components["schemas"]["Plan"] | null;
            /** Current Period End */
            current_period_end: string | null;
            /** Ends At */
            ends_at: string | null;
            limits: components["schemas"]["PlanLimitsView"];
            /** Monthly Cents */
            monthly_cents: number;
            paid_plan: components["schemas"]["Plan"] | null;
            plan: components["schemas"]["Plan"];
            plan_after: components["schemas"]["Plan"] | null;
            /** Plans */
            plans: components["schemas"]["PlanOfferView"][];
            /** Seats */
            seats: number;
            status: components["schemas"]["SubscriptionStatus"] | null;
        };
        /**
         * CompPlanRequest
         * @description The plan an operator grants without a payment; null, or free, takes
         *     the grant back.
         */
        CompPlanRequest: {
            plan: components["schemas"]["Plan"] | null;
        };
        /**
         * ConfirmTotpRequest
         * @description The first code from the authenticator, which confirms the secret.
         */
        ConfirmTotpRequest: {
            /** Totp Code */
            totp_code: string;
        };
        /**
         * CreateOrgRequest
         * @description An org with its owner, as `bootstrap` seeds one. The owner's identity
         *     is created with the password, or kept with its own when the email is
         *     known already.
         */
        CreateOrgRequest: {
            /** Name */
            name: string;
            /** Owner Email */
            owner_email: string;
            /** Owner Name */
            owner_name: string;
            /** Owner Password */
            owner_password: string;
            /** Slug */
            slug: string;
        };
        /**
         * CredentialKind
         * @enum {string}
         */
        CredentialKind: "api_key" | "session_token" | "login" | "socket_ticket" | "operator_token" | "internal";
        /**
         * DeliveryReceivedView
         * @description The delivery checked out and is queued; the processor stops retrying.
         */
        DeliveryReceivedView: {
            /** Received */
            received: boolean;
        };
        /**
         * EventView
         * @description One record of the tenant's append-only stream, paged by `after_seq`.
         *     `kind` is "<namespace>.<entity>.<action>", or an audit kind; the payload
         *     stays inside, an event is a record and not a second read path. The rename
         *     from `entity`/`entity_id`/`action` stayed under `/v1` (ADR 0006).
         */
        EventView: {
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /** Kind */
            kind: string;
            /**
             * Produced At
             * Format: date-time
             */
            produced_at: string;
            /** Seq */
            seq: number;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
        };
        /**
         * ExchangeSessionRequest
         * @description The org to enter. Presented with the sign-in credential, it opens the
         *     first session; presented with a session, it is a switch, and that session
         *     ends in the same write.
         */
        ExchangeSessionRequest: {
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdentityView
         * @description The person behind the caller's user; never carries the password hash.
         *     `operator_role` is the allowlist entry: null for a person who is not an
         *     operator.
         */
        IdentityView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            operator_role: components["schemas"]["OperatorRole"] | null;
        };
        /**
         * IssuedApiKeyView
         * @description The key in the clear is present on the first response only: the stored
         *     outcome of the create carries no secret, so a replay under the same
         *     Idempotency-Key answers with `key` null and `Idempotent-Replayed: true`. A
         *     client that lost the first response revokes the key and issues another.
         */
        IssuedApiKeyView: {
            api_key: components["schemas"]["ApiKeyView"];
            /** Key */
            key: string | null;
        };
        /**
         * IssuedLoginView
         * @description Carries the freshly minted login credential in the clear, once.
         */
        IssuedLoginView: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Memberships */
            memberships: components["schemas"]["MembershipChoiceView"][];
            /** Token */
            token: string;
        };
        /**
         * IssuedOperatorTokenView
         * @description The token in the clear on the first response only; a replay under the
         *     same Idempotency-Key answers with `token` null. A client that lost the
         *     first answer mints another; the lost one expires within the hour.
         */
        IssuedOperatorTokenView: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            permission: components["schemas"]["OperatorRole"];
            /** Token */
            token: string | null;
        };
        /** IssuedSessionView */
        IssuedSessionView: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            org: components["schemas"]["OrgView"];
            role: components["schemas"]["Role"];
            /** Token */
            token: string;
            user: components["schemas"]["UserView"];
        };
        /**
         * IssuedTicketView
         * @description Carries the freshly minted socket ticket in the clear, once; redeeming
         *     it opens the channel and re-checks the credential behind it.
         */
        IssuedTicketView: {
            /** Expires In Seconds */
            expires_in_seconds: number;
            /** Ticket */
            ticket: string;
        };
        /**
         * IssuedTotpSecretView
         * @description A freshly minted TOTP secret, once, as the `otpauth://` URI an
         *     authenticator app reads. A replay carries none.
         */
        IssuedTotpSecretView: {
            /** Otpauth Uri */
            otpauth_uri: string | null;
        };
        /**
         * LoginRequest
         * @description An email and a password, and the code from an authenticator when the
         *     identity has a second factor enrolled. A tenant's sign-in needs none; the
         *     operator plane admits an enrolled operator only on a sign-in that
         *     verified one. A code used once is refused.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Totp Code */
            totp_code?: string | null;
        };
        /** MeView */
        MeView: {
            /** App */
            app: string;
            org: components["schemas"]["OrgView"];
            /** Permissions */
            permissions: components["schemas"]["Permission"][];
            role: components["schemas"]["Role"];
            user: components["schemas"]["UserView"];
        };
        /**
         * MembershipChoicePageView
         * @description One page of the signed-in person's places, each the org, the user, and
         *     the role: the same choice a sign-in answers with. `next_cursor` as on
         *     `UserPageView`.
         */
        MembershipChoicePageView: {
            /** Items */
            items: components["schemas"]["MembershipChoiceView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** MembershipChoiceView */
        MembershipChoiceView: {
            org: components["schemas"]["OrgView"];
            role: components["schemas"]["Role"];
            user: components["schemas"]["UserView"];
        };
        /**
         * MembershipPageView
         * @description One page of the tenant's memberships, by user id; `next_cursor` as on
         *     `UserPageView`. A page read with the same limit as a page of users
         *     covers the same members, so roles pair with members page for page.
         */
        MembershipPageView: {
            /** Items */
            items: components["schemas"]["MembershipView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** MembershipView */
        MembershipView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["Role"];
            /** Teams */
            teams: string[];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * MintOperatorTokenRequest
         * @description One permission, never wider than the caller's entry (`write` implies
         *     `read`), and a lifetime of at most an hour, an hour when absent.
         */
        MintOperatorTokenRequest: {
            /** Expires In */
            expires_in?: number | null;
            permission: components["schemas"]["OperatorRole"];
        };
        /**
         * MoveTaskRequest
         * @description Places an open task right after `after_id`; null puts it at the top.
         *     `expected_version` is the moved task's as the caller read it: 412
         *     `precondition_failed` when the task changed since, and 422
         *     `validation_failed` when the request names no version.
         */
        MoveTaskRequest: {
            /** After Id */
            after_id?: string | null;
            /** Expected Version */
            expected_version?: number | null;
        };
        /** OpenPortalRequest */
        OpenPortalRequest: {
            /** Return Url */
            return_url: string;
        };
        /**
         * OperatorBillingView
         * @description One org's plan, as the operator plane reads it.
         */
        OperatorBillingView: {
            comped_plan: components["schemas"]["Plan"] | null;
            /** Ends At */
            ends_at: string | null;
            paid_plan: components["schemas"]["Plan"] | null;
            plan: components["schemas"]["Plan"];
            status: components["schemas"]["SubscriptionStatus"] | null;
        };
        /**
         * OperatorEventView
         * @description The same record as an operator reads it, with the two provenance fields
         *     a tenant's own feed leaves out: the request that produced it and the app
         *     it came from, which is what a support investigation correlates on.
         */
        OperatorEventView: {
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /** App */
            app: string;
            /** Kind */
            kind: string;
            /**
             * Produced At
             * Format: date-time
             */
            produced_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Seq */
            seq: number;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
        };
        /**
         * OperatorRole
         * @description What an allowlist entry lets an operator do across every tenant. Write
         *     includes read; the tenancy namespace's table says which permissions each
         *     role holds, as it does for `Role`.
         * @enum {string}
         */
        OperatorRole: "read" | "write";
        /**
         * OperatorView
         * @description Who the operator plane admitted: the identity and what its allowlist
         *     entry grants, so a skill checks it holds the entry it expects before it
         *     reads anything.
         */
        OperatorView: {
            /** Email */
            email: string;
            /**
             * Identity Id
             * Format: uuid
             */
            identity_id: string;
            operator_role: components["schemas"]["OperatorRole"];
        };
        /**
         * OrgPageView
         * @description One page of every org, by id, for the operator plane; `next_cursor` as
         *     on `UserPageView`.
         */
        OrgPageView: {
            /** Items */
            items: components["schemas"]["OrgView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** OrgView */
        OrgView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * PasswordResetView
         * @description Whose password was reset; the reset is audited with the operator.
         */
        PasswordResetView: {
            /** Email */
            email: string;
            /**
             * Identity Id
             * Format: uuid
             */
            identity_id: string;
        };
        /**
         * Permission
         * @enum {string}
         */
        Permission: "read" | "write" | "manage_members" | "manage_keys" | "manage_billing";
        /**
         * Plan
         * @enum {string}
         */
        Plan: "free" | "pro" | "team" | "max";
        /**
         * PlanLimitsView
         * @description A plan's bounds; a null count is no bound.
         */
        PlanLimitsView: {
            /** Active Tasks */
            active_tasks: number | null;
            /** Api Keys */
            api_keys: boolean;
            /** Members */
            members: number | null;
            /** Storage Bytes */
            storage_bytes: number;
        };
        /**
         * PlanOfferView
         * @description One plan on offer: its bounds and its monthly price. A per-seat plan's
         *     `flat_cents` covers up to `included_seats` seats, and past them every
         *     seat is `per_seat_cents`.
         */
        PlanOfferView: {
            /** Flat Cents */
            flat_cents: number;
            /** Included Seats */
            included_seats: number | null;
            limits: components["schemas"]["PlanLimitsView"];
            /** Per Seat Cents */
            per_seat_cents: number;
            plan: components["schemas"]["Plan"];
        };
        /**
         * PlatformSizeView
         * @description How big the platform is, what the first responder to an alarm reads
         *     before it escalates: live tenants and users, and the tasks created and
         *     events produced in the last twenty-four hours, a window that starts at
         *     `since` and ends at the read.
         */
        PlatformSizeView: {
            /** Events Last 24H */
            events_last_24h: number;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /** Tasks Last 24H */
            tasks_last_24h: number;
            /** Tenants */
            tenants: number;
            /** Users */
            users: number;
        };
        /**
         * RedirectView
         * @description Where the person goes next: the processor's hosted page.
         */
        RedirectView: {
            /** Url */
            url: string;
        };
        /**
         * ResetPasswordRequest
         * @description The person, by email, and the password they sign in with from now on.
         */
        ResetPasswordRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "owner" | "admin" | "member" | "viewer" | "service";
        /**
         * SessionView
         * @description Only the hash of a token is ever kept, so a session view carries no secret.
         */
        SessionView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            credential_kind: components["schemas"]["CredentialKind"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revoked At */
            revoked_at: string | null;
        };
        /**
         * SignUpRequest
         * @description A new person, their first org, and their password. The answer is a
         *     sign-in's (`IssuedLoginView`), so the client goes on through the same
         *     choice and exchange. `org_slug` is lower-case letters and digits joined
         *     by hyphens; a held email and a taken slug are both 409. No email is
         *     verified.
         */
        SignUpRequest: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Org Name */
            org_name: string;
            /** Org Slug */
            org_slug: string;
            /** Password */
            password: string;
        };
        /**
         * StartCheckoutRequest
         * @description `return_url` is the portal page the person comes back to, paid or not;
         *     it is one of the portal's own origins, or the request is refused.
         */
        StartCheckoutRequest: {
            plan: components["schemas"]["Plan"];
            /** Return Url */
            return_url: string;
        };
        /**
         * SubscriptionStatus
         * @description The processor's statuses, as it spells them.
         * @enum {string}
         */
        SubscriptionStatus: "incomplete" | "incomplete_expired" | "trialing" | "active" | "past_due" | "canceled" | "unpaid" | "paused";
        /**
         * TaskPageView
         * @description One page of a task list. `next_cursor` fetches the next page of the same
         *     list, open or done, and is null on the last page. The page size is
         *     clamped, and a list the clamp cut still says a page follows.
         */
        TaskPageView: {
            /** Items */
            items: components["schemas"]["TaskView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * TaskScope
         * @description Which tasks a list shows. The org is the team.
         * @enum {string}
         */
        TaskScope: "mine" | "team";
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "open" | "done";
        /** TaskView */
        TaskView: {
            /** Assignee Id */
            assignee_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes: string;
            /** Position */
            position: number;
            status: components["schemas"]["TaskStatus"];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /**
         * TotpConfirmedView
         * @description The second factor is enrolled: from now on the operator plane admits
         *     this identity only on a sign-in that verified a code, so the next
         *     request signs in again with one.
         */
        TotpConfirmedView: {
            /**
             * Confirmed At
             * Format: date-time
             */
            confirmed_at: string;
            /**
             * Identity Id
             * Format: uuid
             */
            identity_id: string;
        };
        /** UpdateMeRequest */
        UpdateMeRequest: {
            /** Display Name */
            display_name: string;
        };
        /** UpdateMembershipRequest */
        UpdateMembershipRequest: {
            role: components["schemas"]["Role"];
        };
        /**
         * UpdateTaskRequest
         * @description A partial update: absent fields are kept. An explicit null
         *     `assignee_id` unassigns the task. The version the update compares with is
         *     the task's as the caller read it, in the `If-Match` header: the update
         *     lands only when the task is still at it, and is refused with 412
         *     `precondition_failed` when another write landed since, so the caller reads
         *     again and decides over the current task. An update that names no version
         *     is refused with 422 `validation_failed`, since it would overwrite blind.
         */
        UpdateTaskRequest: {
            /** Assignee Id */
            assignee_id?: string | null;
            /** Notes */
            notes?: string | null;
            status?: components["schemas"]["TaskStatus"] | null;
            /** Title */
            title?: string | null;
        };
        /**
         * UserPageView
         * @description One page of the tenant's members. `next_cursor` fetches the next page
         *     and is null on the last one, so a client reads every member instead of
         *     whatever a fixed limit happened to cover.
         */
        UserPageView: {
            /** Items */
            items: components["schemas"]["UserView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** UserView */
        UserView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    operator_me_v1_admin_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mint_token_v1_admin_me_tokens_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MintOperatorTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedOperatorTokenView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrol_totp_v1_admin_me_totp_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedTotpSecretView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_totp_v1_admin_me_totp_confirm_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmTotpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpConfirmedView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orgs_v1_admin_orgs_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgPageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_org_v1_admin_orgs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_org_v1_admin_orgs__org_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_org_v1_admin_orgs__org_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_org_billing_v1_admin_orgs__org_id__billing_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorBillingView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_v1_admin_orgs__org_id__events_get: {
        parameters: {
            query?: {
                after_seq?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorEventView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_v1_admin_orgs__org_id__members_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_v1_admin_orgs__org_id__members_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
                "idempotency-key"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comp_plan_v1_admin_orgs__org_id__plan_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorBillingView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_v1_admin_orgs__org_id__tasks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"];
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_v1_admin_password_resets_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    platform_size_v1_admin_size_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformSizeView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_v1_api_keys_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyPageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_key_v1_api_keys_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddApiKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedApiKeyView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_v1_api_keys__api_key_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                api_key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: {
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedLoginView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_memberships_v1_auth_memberships_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipChoicePageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exchange_session_v1_auth_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedSessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_up_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: {
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedLoginView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_billing_v1_billing_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_v1_billing_cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_checkout_v1_billing_checkout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartCheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedirectView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_portal_v1_billing_portal_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenPortalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedirectView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_v1_billing_resume_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_v1_events_get: {
        parameters: {
            query?: {
                after_seq?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_v1_me_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_identity_v1_me_identity_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memberships_v1_memberships_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipPageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_v1_memberships__user_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_membership_v1_memberships__user_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMembershipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_org_v1_orgs_current_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mint_ticket_v1_realtime_tickets_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedTicketView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_v1_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_session_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_v1_tasks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"];
                scope?: components["schemas"]["TaskScope"];
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_v1_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
                /** @description The version the caller read, as an entity tag: `"3"`. 412 `precondition_failed` when the record changed since. */
                "If-Match"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_v1_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
                /** @description The version the caller read, as an entity tag: `"3"`. 412 `precondition_failed` when the record changed since. */
                "If-Match"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_task_v1_tasks__task_id__move_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_v1_users_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-app"?: string | null;
                "x-app-version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_delivery_webhooks_stripe_post: {
        parameters: {
            query?: never;
            header?: {
                "Stripe-Signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryReceivedView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
