# generated by datamodel-codegen:
#   filename:  openapi.json

from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AccountDeletedView(BaseModel):
    """
    The account is gone: `deleted_at` is when. The database's backups
    still hold it until they expire, seven days on. `provider_logout_url` is
    where the browser goes next, as on a sign-out; null when the sign-in
    left no session there.
    """
    deleted_at: Annotated[AwareDatetime, Field(title='Deleted At')]
    provider_logout_url: Annotated[str | None, Field(title='Provider Logout Url')] = None


class TtlDays(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=90, title='Ttl Days')]


class ConfirmTotpRequest(BaseModel):
    """
    The first code from the authenticator, which confirms the secret.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    totp_code: Annotated[str, Field(max_length=6, min_length=6, title='Totp Code')]


class CreateOrgRequest(BaseModel):
    """
    An org with its owner, as `bootstrap` seeds one. The owner's identity
    is created with its personal org when the email is new; the owner signs
    in through the identity provider with the address.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]
    owner_email: Annotated[str, Field(min_length=1, title='Owner Email')]
    owner_name: Annotated[str, Field(max_length=200, min_length=1, title='Owner Name')]
    slug: Annotated[str, Field(max_length=100, min_length=1, title='Slug')]


class Slug(RootModel[str]):
    root: Annotated[str, Field(max_length=48, min_length=1, title='Slug')]


class CreateTeamOrgRequest(BaseModel):
    """
    A team org the caller makes and owns. `slug` is lower-case letters and
    digits joined by hyphens; left out, one is made from the name. A taken
    slug is 409.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]
    slug: Annotated[Slug | None, Field(title='Slug')] = None


class CredentialKind(StrEnum):
    api_key = 'api_key'
    session_token = 'session_token'
    login = 'login'
    socket_ticket = 'socket_ticket'
    operator_token = 'operator_token'
    internal = 'internal'


class ReturnTo(RootModel[str]):
    root: Annotated[str, Field(max_length=2000, min_length=1, title='Return To')]


class DeleteAccountRequest(BaseModel):
    """
    The account's email as the person typed it, which is how they say
    they mean it; and, as on the sign-out, where the identity provider sends
    the browser once it has ended its own session.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[str, Field(max_length=320, min_length=1, title='Email')]
    return_to: Annotated[ReturnTo | None, Field(title='Return To')] = None


class DeleteOrgRequest(BaseModel):
    """
    The org's name as its owner typed it, which is how they say they mean
    it.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]


class DeliveryReceivedView(BaseModel):
    """
    The delivery checked out and is queued; the provider stops retrying.
    """
    received: Annotated[bool, Field(title='Received')]


class DevSignInRequest(BaseModel):
    """
    Local and test only: a sign-in by address alone, with no browser round
    trip, for the seed, the traffic generator, and the tests. A
    person nobody knew is made, with their personal org. A deployed
    environment never serves it: the route answers 404 there, and the
    process refuses to start with it on.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: Annotated[str | None, Field(max_length=200, title='Display Name')] = ''
    email: Annotated[str, Field(max_length=320, min_length=3, title='Email')]


class DeviceSignInView(BaseModel):
    """
    The start of a sign-in for a device with no browser, the command
    line. The person opens `verification_uri_complete` (or
    `verification_uri` and types `user_code`) in any browser; the device
    keeps `device_code` to itself and asks `POST /v1/auth/device/token`
    with it every `interval` seconds, for at most `expires_in` seconds.
    """
    device_code: Annotated[str, Field(title='Device Code')]
    expires_in: Annotated[int, Field(title='Expires In')]
    interval: Annotated[int, Field(title='Interval')]
    user_code: Annotated[str, Field(title='User Code')]
    verification_uri: Annotated[str, Field(title='Verification Uri')]
    verification_uri_complete: Annotated[str, Field(title='Verification Uri Complete')]


class DeviceTokenRequest(BaseModel):
    """
    The device code a device sign-in started with. The answer is a
    sign-in's once the person confirmed it; before that, 400
    `sign_in_pending` (or `sign_in_slow_down`: ask less often), and 401
    `sign_in_refused` when they declined or it expired.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    device_code: Annotated[str, Field(max_length=500, min_length=1, title='Device Code')]


class EventView(BaseModel):
    """
    One record of the tenant's append-only stream, paged by `after_seq`.
    `kind` is "<namespace>.<entity>.<action>", or an audit kind; the payload
    stays inside, an event is a record and not a second read path.
    """
    actor_id: Annotated[UUID, Field(title='Actor Id')]
    kind: Annotated[str, Field(title='Kind')]
    produced_at: Annotated[AwareDatetime, Field(title='Produced At')]
    seq: Annotated[int, Field(title='Seq')]
    target_id: Annotated[UUID, Field(title='Target Id')]


class ExchangeSessionRequest(BaseModel):
    """
    The org to enter. Presented with the sign-in credential, it opens the
    first session; presented with a session, it is a switch, and that session
    ends in the same write.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    org_id: Annotated[UUID, Field(title='Org Id')]


class FilePurpose(StrEnum):
    """
    Which context a file came from. The purpose decides the bounds an
    upload is held to and what `subject_id` names. A product adds a purpose
    per kind of file it keeps, with its bounds (`media.rules.BOUNDS`).
    """
    upload = 'upload'


class FileStatus(StrEnum):
    pending = 'pending'
    stored = 'stored'


class FileView(BaseModel):
    """
    A file the tenant keeps: its name, type, and size, never its bytes and
    never where they live. `status` is `pending` until the upload is
    confirmed, then `stored`.
    """
    content_type: Annotated[str, Field(title='Content Type')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')]
    extension: Annotated[str, Field(title='Extension')]
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    purpose: FilePurpose
    size_bytes: Annotated[int, Field(title='Size Bytes')]
    status: FileStatus
    subject_id: Annotated[UUID | None, Field(title='Subject Id')]


class FlagsView(BaseModel):
    """
    The session's flags that a client may read, evaluated for its org and
    its user. A flag read on the server alone is never in it.
    """
    flags: Annotated[dict[str, bool], Field(description="Each flag marked for clients, by name, and its value for the session's org and user.", title='Flags')]


class InvitationState(StrEnum):
    pending = 'pending'
    accepted = 'accepted'
    revoked = 'revoked'


class IssuedDownloadView(BaseModel):
    """
    A link to the file's bytes that works until `expires_at`. A null `url`
    means the store cannot sign one: the bytes come from
    `GET /v1/media/files/{id}/content`.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    url: Annotated[str | None, Field(title='Url')]


class IssuedTicketView(BaseModel):
    """
    Carries the freshly minted socket ticket in the clear, once; redeeming
    it opens the channel and re-checks the credential behind it.
    """
    expires_in_seconds: Annotated[int, Field(title='Expires In Seconds')]
    ticket: Annotated[str, Field(title='Ticket')]


class IssuedTotpSecretView(BaseModel):
    """
    A freshly minted TOTP secret, once, as the `otpauth://` URI an
    authenticator app reads. A replay carries none.
    """
    otpauth_uri: Annotated[str | None, Field(title='Otpauth Uri')]


class LogoutRequest(BaseModel):
    """
    Where the identity provider sends the browser once it has ended its own
    session: this environment's portal page for it, and nothing else. Left
    out, the provider sends it to its default sign-out address.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    return_to: Annotated[ReturnTo | None, Field(title='Return To')] = None


class ExpiresIn(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=3600, title='Expires In')]


class OperatorEventView(BaseModel):
    """
    The same record as an operator reads it, with the two provenance fields
    a tenant's own feed leaves out: the request that produced it and the app
    it came from, which is what a support investigation correlates on.
    """
    actor_id: Annotated[UUID, Field(title='Actor Id')]
    app: Annotated[str, Field(title='App')]
    kind: Annotated[str, Field(title='Kind')]
    produced_at: Annotated[AwareDatetime, Field(title='Produced At')]
    request_id: Annotated[UUID, Field(title='Request Id')]
    seq: Annotated[int, Field(title='Seq')]
    target_id: Annotated[UUID, Field(title='Target Id')]


class OperatorRole(StrEnum):
    """
    What an allowlist entry lets an operator do across every tenant. Write
    includes read; the tenancy namespace's table says which permissions each
    role holds, as it does for `Role`.
    """
    read = 'read'
    write = 'write'


class OperatorTokenView(BaseModel):
    """
    One operator token as its operator reads it: never the secret, which is
    kept as its digest. `revoked_at` is set once it was ended.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    permission: OperatorRole
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class OperatorView(BaseModel):
    """
    Who the operator plane admitted: the identity and what its allowlist
    entry grants, so a skill checks it holds the entry it expects before it
    reads anything.
    """
    email: Annotated[str, Field(title='Email')]
    identity_id: Annotated[UUID, Field(title='Identity Id')]
    operator_role: OperatorRole


class OrgKind(StrEnum):
    """
    What an org is for. Every person has exactly one personal org, made
    with them; every other org is a team org, made on purpose.
    """
    personal = 'personal'
    team = 'team'


class OrgView(BaseModel):
    """
    `kind` says what the org is for: every person has one `personal` org,
    made with them, which is never deleted and never changes hands; every
    other org is a `team` org.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')] = None
    id: Annotated[UUID, Field(title='Id')]
    kind: OrgKind
    name: Annotated[str, Field(title='Name')]
    slug: Annotated[str, Field(title='Slug')]


class OwnedOrgRef(BaseModel):
    """
    An org named in a refusal: enough to find it and to say which.
    """
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    slug: Annotated[str, Field(title='Slug')]


class Permission(StrEnum):
    read = 'read'
    write = 'write'
    manage_members = 'manage_members'
    manage_keys = 'manage_keys'


class PlatformSizeView(BaseModel):
    """
    How big the platform is, what the first responder to an alarm reads
    before it escalates: live tenants and users, and the events produced in
    the twenty-four hours from `since` to `counted_at`. The maintenance
    worker counts it every few minutes, and this is its latest count:
    `counted_at` says how old the answer is.
    """
    counted_at: Annotated[AwareDatetime, Field(title='Counted At')]
    events_last_24h: Annotated[int, Field(title='Events Last 24H')]
    since: Annotated[AwareDatetime, Field(title='Since')]
    tenants: Annotated[int, Field(title='Tenants')]
    users: Annotated[int, Field(title='Users')]


class PurposeUsageView(BaseModel):
    count: Annotated[int, Field(title='Count')]
    pending_count: Annotated[int, Field(title='Pending Count')]
    pending_size_bytes: Annotated[int, Field(title='Pending Size Bytes')]
    purpose: FilePurpose
    size_bytes: Annotated[int, Field(title='Size Bytes')]


class Role(StrEnum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'
    viewer = 'viewer'
    service = 'service'


class SecondFactorRequest(BaseModel):
    """
    The code from an authenticator, presented with a sign-in credential.
    The answer is a new sign-in that records the verified code, which the
    operator plane asks of an enrolled operator. A code used once is
    refused.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    totp_code: Annotated[str, Field(max_length=6, min_length=6, title='Totp Code')]


class SessionView(BaseModel):
    """
    Only the hash of a token is ever kept, so a session view carries no secret.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    credential_kind: CredentialKind
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class InvitationToken(RootModel[str]):
    root: Annotated[str, Field(max_length=500, title='Invitation Token')]


class SignInCallbackRequest(BaseModel):
    """
    The code the browser brought back to the callback, and the verifier
    the sign-in's start answered with, which the API exchanges with the
    identity provider, server-side. The answer is a
    sign-in's (`IssuedLoginView`); a person nobody knew is signed up by it,
    with their personal org.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[str, Field(max_length=500, min_length=1, title='Code')]
    code_verifier: Annotated[str, Field(max_length=128, min_length=43, title='Code Verifier')]
    invitation_token: Annotated[InvitationToken | None, Field(title='Invitation Token')] = None


class SignInStartRequest(BaseModel):
    """
    The start of a sign-in at the identity provider. `redirect_uri` is where
    the browser comes back with a code: this environment's portal callback,
    and nothing else. `state` is the caller's own random value, kept by the
    tab that started the sign-in and compared when the browser comes back,
    which binds the round trip to that tab; it may carry nothing else.
    `invitation_token` is the one an invitation's link carried, and
    `sign_up` opens the provider on its sign-up screen.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    invitation_token: Annotated[InvitationToken | None, Field(title='Invitation Token')] = None
    redirect_uri: Annotated[str, Field(max_length=2000, min_length=1, title='Redirect Uri')]
    sign_up: Annotated[bool | None, Field(title='Sign Up')] = False
    state: Annotated[str, Field(max_length=200, min_length=16, title='State')]


class SignInStartView(BaseModel):
    """
    Where the browser goes next, the identity provider's sign-in, and the
    PKCE verifier the tab keeps beside its state and sends back with the
    code. The provider holds only the verifier's digest, so a code is worth
    nothing to anyone who does not hold it.
    """
    authorization_url: Annotated[str, Field(title='Authorization Url')]
    code_verifier: Annotated[str, Field(title='Code Verifier')]


class SignedOutView(BaseModel):
    """
    The credential that ended, a session, a sign-in, or an operator
    token, and `provider_logout_url`: where the browser goes next to end the
    identity provider's session behind it, so the next sign-in on this
    browser asks who it is. Null when the sign-in left no session there
    (the device sign-in, the local sign-in, an operator token). It names the
    provider's session, which is not a secret.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    credential_kind: CredentialKind
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    provider_logout_url: Annotated[str | None, Field(title='Provider Logout Url')] = None
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class Intent(StrEnum):
    sso = 'sso'
    domain_verification = 'domain_verification'


class SsoLinkRequest(BaseModel):
    """
    What the identity provider's admin portal opens on: the single sign-on
    connection (`sso`) or the org's domains (`domain_verification`), and the
    page of this environment's portal it links back to.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    intent: Annotated[Intent, Field(title='Intent')]
    return_url: Annotated[str, Field(max_length=2000, min_length=1, title='Return Url')]


class SsoLinkView(BaseModel):
    """
    A short-lived link to the admin portal; open it at once.
    """
    url: Annotated[str, Field(title='Url')]


class StartUploadRequest(BaseModel):
    """
    An upload to start: the file's name as the uploader had it, its type,
    and its size in bytes. The type must be one the purpose accepts and match
    the name's extension; the size is the most the store will take.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    content_type: Annotated[str, Field(max_length=255, min_length=1, title='Content Type')]
    name: Annotated[str, Field(max_length=255, min_length=1, title='Name')]
    size_bytes: Annotated[int, Field(gt=0, title='Size Bytes')]


class StorageUsageView(BaseModel):
    """
    What the org keeps in the store, counted from its files: the stored ones
    per purpose and in total, and the uploads started and not yet confirmed.
    A removed file stops counting at once.
    """
    pending_size_bytes: Annotated[int, Field(title='Pending Size Bytes')]
    purposes: Annotated[list[PurposeUsageView], Field(title='Purposes')]
    total_count: Annotated[int, Field(title='Total Count')]
    total_size_bytes: Annotated[int, Field(title='Total Size Bytes')]


class StreamTruncatedDetail(BaseModel):
    """
    What a `stream_truncated` refusal carries: the floor, the highest seq
    trimmed from the stream, and the head. A client drops its cursor, reads
    afresh what it shows, and goes on from the head.
    """
    floor: Annotated[int, Field(title='Floor')]
    head: Annotated[int, Field(title='Head')]


class TotpConfirmedView(BaseModel):
    """
    The second factor is enrolled: from now on the operator plane admits
    this identity only on a sign-in that verified a code, so the next
    request signs in again with one.
    """
    confirmed_at: Annotated[AwareDatetime, Field(title='Confirmed At')]
    identity_id: Annotated[UUID, Field(title='Identity Id')]


class UpdateIdentityRequest(BaseModel):
    """
    Where the person is, as an IANA name ("Europe/Istanbul"): the portal
    sends the browser's own on sign-in, and a time shown or sent to the
    person is in it; with none sent, in UTC. A name that is not one is
    422.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    time_zone: Annotated[str, Field(max_length=64, min_length=1, title='Time Zone')]


class UpdateMeRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: Annotated[str, Field(max_length=200, min_length=1, title='Display Name')]


class UpdateMembershipRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: Role


class UploadFieldView(BaseModel):
    name: Annotated[str, Field(title='Name')]
    value: Annotated[str, Field(title='Value')]


class UserView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    display_name: Annotated[str, Field(title='Display Name')]
    email: Annotated[str, Field(title='Email')]
    id: Annotated[UUID, Field(title='Id')]


class ValidationError(BaseModel):
    ctx: Annotated[dict[str, Any] | None, Field(title='Context')] = None
    input: Annotated[Any | None, Field(title='Input')] = None
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]


class WorkKind(StrEnum):
    NOOP = 'NOOP'
    ORCHESTRATION = 'ORCHESTRATION'
    WAKE_PARKED = 'WAKE_PARKED'
    DELETE_ACCOUNT = 'DELETE_ACCOUNT'
    DELETE_ORG = 'DELETE_ORG'


class WorkStatus(StrEnum):
    queued = 'queued'
    claimed = 'claimed'
    done = 'done'
    failed = 'failed'


class AddApiKeyRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    role: Role
    ttl_days: Annotated[TtlDays | None, Field(title='Ttl Days')] = None


class AddMemberRequest(BaseModel):
    """
    A person in the org, as `add-member` seeds one; the owner and the
    service role are refused, since the one owner is the one the create
    minted.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: Annotated[str, Field(max_length=200, min_length=1, title='Display Name')]
    email: Annotated[str, Field(min_length=1, title='Email')]
    role: Role


class ApiKeyView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    role: Role
    user_id: Annotated[UUID, Field(title='User Id')]


class FilePageView(BaseModel):
    """
    One page of the org's stored files, oldest first. `next_cursor` fetches
    the next page and is null on the last one.
    """
    items: Annotated[list[FileView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class IdentityView(BaseModel):
    """
    The person behind the caller's user. `operator_role` is the allowlist
    entry: null for a person who is not an operator.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    email: Annotated[str, Field(title='Email')]
    id: Annotated[UUID, Field(title='Id')]
    operator_role: OperatorRole | None
    time_zone: Annotated[str | None, Field(title='Time Zone')] = None


class InvitationView(BaseModel):
    """
    A person asked to join the org. The identity provider sent the email
    with the link; `expires_at` is when the link stops working, after which
    the invitation is sent again or replaced.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    email: Annotated[str, Field(title='Email')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    role: Role
    state: InvitationState


class InviteMemberRequest(BaseModel):
    """
    The address to invite and the role the person gets, at most the
    caller's own.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[str, Field(max_length=320, min_length=3, title='Email')]
    role: Role


class IssuedApiKeyView(BaseModel):
    """
    The key in the clear is present on the first response only: the stored
    outcome of the create carries no secret, so a replay under the same
    Idempotency-Key answers with `key` null and `Idempotent-Replayed: true`. A
    client that lost the first response revokes the key and issues another.
    """
    api_key: ApiKeyView
    key: Annotated[str | None, Field(title='Key')]


class IssuedOperatorTokenView(BaseModel):
    """
    The token in the clear, on this answer only; `id` names it afterwards,
    in the list and the revoke, and is no secret. The mint ends the sign-in
    it was given, so a client that lost this answer signs in again for
    another token and revokes the lost one by its id from the list.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    permission: OperatorRole
    token: Annotated[str | None, Field(title='Token')]


class IssuedSessionView(BaseModel):
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    org: OrgView
    role: Role
    token: Annotated[str, Field(title='Token')]
    user: UserView


class IssuedUploadView(BaseModel):
    """
    A form to post the file with, straight to the store: every field, in
    order, then the file as the last field, named `file`. The signed policy
    holds the post to the file's type and at most its size, until
    `expires_at`. A null `url` means the store cannot take a post: the bytes
    go to `PUT /v1/media/files/{id}/content` instead. Then the upload is
    confirmed.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    fields: Annotated[list[UploadFieldView], Field(title='Fields')]
    url: Annotated[str | None, Field(title='Url')]


class LastOwnerDetail(BaseModel):
    """
    What a `last_owner` refusal carries: every team org the person is the
    last owner of, which they hand on or delete before their account goes.
    """
    orgs: Annotated[list[OwnedOrgRef], Field(title='Orgs')]


class MeView(BaseModel):
    app: Annotated[str, Field(title='App')]
    org: OrgView
    permissions: Annotated[list[Permission], Field(title='Permissions')]
    role: Role
    user: UserView


class MembershipChoiceView(BaseModel):
    org: OrgView
    role: Role
    user: UserView


class MembershipView(BaseModel):
    id: Annotated[UUID, Field(title='Id')]
    role: Role
    teams: Annotated[list[UUID], Field(title='Teams')]
    user_id: Annotated[UUID, Field(title='User Id')]


class MintOperatorTokenRequest(BaseModel):
    """
    One permission, never wider than the caller's entry (`write` implies
    `read`), and a lifetime of at most an hour, an hour when absent.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_in: Annotated[ExpiresIn | None, Field(title='Expires In')] = None
    permission: OperatorRole


class OperatorTokenPageView(BaseModel):
    """
    One page of the caller's live operator tokens, newest first;
    `next_cursor` as on `UserPageView`.
    """
    items: Annotated[list[OperatorTokenView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class OperatorWorkItemView(BaseModel):
    """
    One background job as an operator reads it: what it does and for
    which record, where it stands, and how many of its attempts are spent.
    The payload and the claim stay the worker's.
    """
    attempts: Annotated[int, Field(title='Attempts')]
    available_at: Annotated[AwareDatetime, Field(title='Available At')]
    id: Annotated[UUID, Field(title='Id')]
    kind: WorkKind
    last_error: Annotated[str | None, Field(title='Last Error')]
    max_attempts: Annotated[int, Field(title='Max Attempts')]
    status: WorkStatus
    target_id: Annotated[UUID, Field(title='Target Id')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]


class OrgDeletedView(BaseModel):
    """
    The org is gone for everyone in it: `deleted_at` is when. `session` is
    the owner's new session in their personal org, which replaces the one
    that asked, as a switch's does; null when none could be made, and the
    owner signs in again.
    """
    deleted_at: Annotated[AwareDatetime, Field(title='Deleted At')]
    session: IssuedSessionView | None = None


class OrgPageView(BaseModel):
    """
    One page of every org, by id, for the operator plane; `next_cursor` as
    on `UserPageView`.
    """
    items: Annotated[list[OrgView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class UserPageView(BaseModel):
    """
    One page of the tenant's members. `next_cursor` fetches the next page
    and is null on the last one, so a client reads every member instead of
    whatever a fixed limit happened to cover.
    """
    items: Annotated[list[UserView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class ApiKeyPageView(BaseModel):
    """
    One page of the api key list, newest first; `next_cursor` as on
    `UserPageView`.
    """
    items: Annotated[list[ApiKeyView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class ErrorBody(BaseModel):
    code: Annotated[str, Field(title='Code')]
    last_owner: LastOwnerDetail | None = None
    message: Annotated[str, Field(title='Message')]
    request_id: Annotated[UUID, Field(title='Request Id')]
    stream: StreamTruncatedDetail | None = None


class ErrorResponse(BaseModel):
    error: ErrorBody


class InvitationPageView(BaseModel):
    """
    One page of the org's pending invitations, newest first; `next_cursor`
    as on `UserPageView`.
    """
    items: Annotated[list[InvitationView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class IssuedLoginView(BaseModel):
    """
    Carries the freshly minted login credential in the clear, once.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    memberships: Annotated[list[MembershipChoiceView], Field(title='Memberships')]
    token: Annotated[str, Field(title='Token')]


class MembershipChoicePageView(BaseModel):
    """
    One page of the signed-in person's places, each the org, the user, and
    the role: the same choice a sign-in answers with. `next_cursor` as on
    `UserPageView`.
    """
    items: Annotated[list[MembershipChoiceView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class MembershipPageView(BaseModel):
    """
    One page of the tenant's memberships, by user id; `next_cursor` as on
    `UserPageView`. A page read with the same limit as a page of users
    covers the same members, so roles pair with members page for page.
    """
    items: Annotated[list[MembershipView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]
