# generated by datamodel-codegen:
#   filename:  openapi.json

from datetime import date
from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AccountDeletedView(BaseModel):
    """
    The account is gone: `deleted_at` is when. The database's backups
    still hold it until they expire, seven days on. `provider_logout_url` is
    where the browser goes next, as on a sign-out; null when the sign-in
    left no session there.
    """
    deleted_at: Annotated[AwareDatetime, Field(title='Deleted At')]
    provider_logout_url: Annotated[str | None, Field(title='Provider Logout Url')] = None


class TtlDays(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=90, title='Ttl Days')]


class AddFileRequest(BaseModel):
    """
    An upload to start: the file's name as the uploader had it, its type,
    and its size in bytes. The type must be one the purpose accepts and match
    the name's extension; the size is the most the store will take.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    content_type: Annotated[str, Field(max_length=255, min_length=1, title='Content Type')]
    name: Annotated[str, Field(max_length=255, min_length=1, title='Name')]
    size_bytes: Annotated[int, Field(gt=0, title='Size Bytes')]


class AddTaskRequest(BaseModel):
    """
    `due_on` is the day the task is due, `YYYY-MM-DD`, never a time. It
    schedules one reminder at nine in the morning of that day, in the time
    zone of the person the task is for (the assignee, or the creator), pushed
    to every open screen of the org and posted to its Slack channel when one
    is connected.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    assignee_id: Annotated[UUID | None, Field(title='Assignee Id')] = None
    due_on: Annotated[date | None, Field(title='Due On')] = None
    notes: Annotated[str | None, Field(title='Notes')] = ''
    title: Annotated[str, Field(max_length=500, title='Title')]


class BulkAction(StrEnum):
    """
    What a bulk change does to each task: the status a single edit would
    write.
    """
    complete = 'complete'
    reopen = 'reopen'


class Ids(RootModel[list[UUID]]):
    root: Annotated[list[UUID], Field(max_length=1000, title='Ids')]


class ConfirmTotpRequest(BaseModel):
    """
    The first code from the authenticator, which confirms the secret.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    totp_code: Annotated[str, Field(max_length=6, min_length=6, title='Totp Code')]


class CreateOrgRequest(BaseModel):
    """
    An org with its owner, as `bootstrap` seeds one. The owner's identity
    is created with its personal org when the email is new; the owner signs
    in through the identity provider with the address.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]
    owner_email: Annotated[str, Field(min_length=1, title='Owner Email')]
    owner_name: Annotated[str, Field(max_length=200, min_length=1, title='Owner Name')]
    slug: Annotated[str, Field(max_length=100, min_length=1, title='Slug')]


class Slug(RootModel[str]):
    root: Annotated[str, Field(max_length=48, min_length=1, title='Slug')]


class CreateTeamOrgRequest(BaseModel):
    """
    A team org the caller makes and owns. `slug` is lower-case letters and
    digits joined by hyphens; left out, one is made from the name. A taken
    slug is 409.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]
    slug: Annotated[Slug | None, Field(title='Slug')] = None


class CredentialKind(StrEnum):
    api_key = 'api_key'
    session_token = 'session_token'
    login = 'login'
    socket_ticket = 'socket_ticket'
    operator_token = 'operator_token'
    internal = 'internal'


class ReturnTo(RootModel[str]):
    root: Annotated[str, Field(max_length=2000, min_length=1, title='Return To')]


class DeleteAccountRequest(BaseModel):
    """
    The account's email as the person typed it, which is how they say
    they mean it; and, as on the sign-out, where the identity provider sends
    the browser once it has ended its own session.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[str, Field(max_length=320, min_length=1, title='Email')]
    return_to: Annotated[ReturnTo | None, Field(title='Return To')] = None


class DeleteOrgRequest(BaseModel):
    """
    The org's name as its owner typed it, which is how they say they mean
    it.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]


class DeliveryReceivedView(BaseModel):
    """
    The delivery checked out and is queued; the processor stops retrying.
    """
    received: Annotated[bool, Field(title='Received')]


class DevSignInRequest(BaseModel):
    """
    Local and test only: a sign-in by address alone, with no browser round
    trip, for the seed, the demos, the traffic generator, and the tests. A
    person nobody knew is made, with their personal org. A deployed
    environment never serves it: the route answers 404 there, and the
    process refuses to start with it on.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: Annotated[str | None, Field(max_length=200, title='Display Name')] = ''
    email: Annotated[str, Field(max_length=320, min_length=3, title='Email')]


class DeviceSignInView(BaseModel):
    """
    The start of a sign-in for a device with no browser, the command
    line. The person opens `verification_uri_complete` (or
    `verification_uri` and types `user_code`) in any browser; the device
    keeps `device_code` to itself and asks `POST /v1/auth/device/token`
    with it every `interval` seconds, for at most `expires_in` seconds.
    """
    device_code: Annotated[str, Field(title='Device Code')]
    expires_in: Annotated[int, Field(title='Expires In')]
    interval: Annotated[int, Field(title='Interval')]
    user_code: Annotated[str, Field(title='User Code')]
    verification_uri: Annotated[str, Field(title='Verification Uri')]
    verification_uri_complete: Annotated[str, Field(title='Verification Uri Complete')]


class DeviceTokenRequest(BaseModel):
    """
    The device code a device sign-in started with. The answer is a
    sign-in's once the person confirmed it; before that, 400
    `sign_in_pending` (or `sign_in_slow_down`: ask less often), and 401
    `sign_in_refused` when they declined or it expired.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    device_code: Annotated[str, Field(max_length=500, min_length=1, title='Device Code')]


class EventView(BaseModel):
    """
    One record of the tenant's append-only stream, paged by `after_seq`.
    `kind` is "<namespace>.<entity>.<action>", or an audit kind; the payload
    stays inside, an event is a record and not a second read path. The rename
    from `entity`/`entity_id`/`action` stayed under `/v1` (ADR 0006).
    """
    actor_id: Annotated[UUID, Field(title='Actor Id')]
    kind: Annotated[str, Field(title='Kind')]
    produced_at: Annotated[AwareDatetime, Field(title='Produced At')]
    seq: Annotated[int, Field(title='Seq')]
    target_id: Annotated[UUID, Field(title='Target Id')]


class ExchangeSessionRequest(BaseModel):
    """
    The org to enter. Presented with the sign-in credential, it opens the
    first session; presented with a session, it is a switch, and that session
    ends in the same write.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    org_id: Annotated[UUID, Field(title='Org Id')]


class FailReason(StrEnum):
    """
    Why a record ended without finishing: a bound, never a guard.
    """
    file_too_large = 'file_too_large'
    too_many_rows = 'too_many_rows'
    not_csv = 'not_csv'
    no_title_column = 'no_title_column'
    file_gone = 'file_gone'
    defect = 'defect'


class FilePurpose(StrEnum):
    """
    Which domain context a file came from. The purpose decides the bounds an
    upload is held to and what `subject_id` names.
    """
    task_attachment = 'task_attachment'
    voice_dictation = 'voice_dictation'
    task_import = 'task_import'


class FileStatus(StrEnum):
    pending = 'pending'
    stored = 'stored'


class FileView(BaseModel):
    """
    A file the tenant keeps: its name, type, and size, never its bytes and
    never where they live. `status` is `pending` until the upload is
    confirmed, then `stored`.
    """
    content_type: Annotated[str, Field(title='Content Type')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')]
    extension: Annotated[str, Field(title='Extension')]
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    purpose: FilePurpose
    size_bytes: Annotated[int, Field(title='Size Bytes')]
    status: FileStatus
    subject_id: Annotated[UUID | None, Field(title='Subject Id')]


class InvitationState(StrEnum):
    pending = 'pending'
    accepted = 'accepted'
    revoked = 'revoked'


class IssuedDownloadView(BaseModel):
    """
    A link to the file's bytes that works until `expires_at`. A null `url`
    means the store cannot sign one: the bytes come from
    `GET /v1/media/files/{id}/content`.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    url: Annotated[str | None, Field(title='Url')]


class IssuedTicketView(BaseModel):
    """
    Carries the freshly minted socket ticket in the clear, once; redeeming
    it opens the channel and re-checks the credential behind it.
    """
    expires_in_seconds: Annotated[int, Field(title='Expires In Seconds')]
    ticket: Annotated[str, Field(title='Ticket')]


class IssuedTotpSecretView(BaseModel):
    """
    A freshly minted TOTP secret, once, as the `otpauth://` URI an
    authenticator app reads. A replay carries none.
    """
    otpauth_uri: Annotated[str | None, Field(title='Otpauth Uri')]


class LogoutRequest(BaseModel):
    """
    Where the identity provider sends the browser once it has ended its own
    session: this environment's portal page for it, and nothing else. Left
    out, the provider sends it to its default sign-out address.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    return_to: Annotated[ReturnTo | None, Field(title='Return To')] = None


class ExpiresIn(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=3600, title='Expires In')]


class ExpectedVersion(RootModel[int]):
    root: Annotated[int, Field(ge=1, title='Expected Version')]


class MoveTaskRequest(BaseModel):
    """
    Places an open task right after `after_id`; null puts it at the top.
    `expected_version` is the moved task's as the caller read it: 412
    `precondition_failed` when the task changed since, and 422
    `validation_failed` when the request names no version.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    after_id: Annotated[UUID | None, Field(title='After Id')] = None
    expected_version: Annotated[ExpectedVersion | None, Field(title='Expected Version')] = None


class FlowEnum(StrEnum):
    payment_method_update = 'payment_method_update'


class Flow(RootModel[FlowEnum | None]):
    root: Annotated[FlowEnum | None, Field(title='Flow')] = None


class OpenPortalRequest(BaseModel):
    """
    `flow` opens the processor's page on one task and comes back to
    `return_url` when it is done; without it, the page's home.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    flow: Annotated[Flow | None, Field(title='Flow')] = None
    return_url: Annotated[str, Field(max_length=2000, min_length=1, title='Return Url')]


class OperatorEventView(BaseModel):
    """
    The same record as an operator reads it, with the two provenance fields
    a tenant's own feed leaves out: the request that produced it and the app
    it came from, which is what a support investigation correlates on.
    """
    actor_id: Annotated[UUID, Field(title='Actor Id')]
    app: Annotated[str, Field(title='App')]
    kind: Annotated[str, Field(title='Kind')]
    produced_at: Annotated[AwareDatetime, Field(title='Produced At')]
    request_id: Annotated[UUID, Field(title='Request Id')]
    seq: Annotated[int, Field(title='Seq')]
    target_id: Annotated[UUID, Field(title='Target Id')]


class OperatorRole(StrEnum):
    """
    What an allowlist entry lets an operator do across every tenant. Write
    includes read; the tenancy namespace's table says which permissions each
    role holds, as it does for `Role`.
    """
    read = 'read'
    write = 'write'


class OperatorTokenView(BaseModel):
    """
    One operator token as its operator reads it: never the secret, which is
    kept as its digest. `revoked_at` is set once it was ended.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    permission: OperatorRole
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class OperatorView(BaseModel):
    """
    Who the operator plane admitted: the identity and what its allowlist
    entry grants, so a skill checks it holds the entry it expects before it
    reads anything.
    """
    email: Annotated[str, Field(title='Email')]
    identity_id: Annotated[UUID, Field(title='Identity Id')]
    operator_role: OperatorRole


class OrchestrationStatus(StrEnum):
    running = 'running'
    parked = 'parked'
    succeeded = 'succeeded'
    failed = 'failed'


class OrgKind(StrEnum):
    """
    What an org is for. Every person has exactly one personal org, made
    with them; every other org is a team org, made on purpose.
    """
    personal = 'personal'
    team = 'team'


class OrgView(BaseModel):
    """
    `kind` says what the org is for: every person has one `personal` org,
    made with them, which is never deleted and never changes hands; every
    other org is a `team` org.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')] = None
    id: Annotated[UUID, Field(title='Id')]
    kind: OrgKind
    name: Annotated[str, Field(title='Name')]
    slug: Annotated[str, Field(title='Slug')]


class OwnedOrgRef(BaseModel):
    """
    An org named in a refusal: enough to find it and to say which.
    """
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    slug: Annotated[str, Field(title='Slug')]


class ParkReason(StrEnum):
    """
    Why a record waits, and so what wakes it.
    """
    plan_limit = 'plan_limit'


class Permission(StrEnum):
    read = 'read'
    write = 'write'
    manage_members = 'manage_members'
    manage_keys = 'manage_keys'
    manage_billing = 'manage_billing'


class Plan(StrEnum):
    free = 'free'
    pro = 'pro'
    team = 'team'
    max = 'max'


class PlanLimitDetail(BaseModel):
    """
    What a `plan_limit_reached` refusal carries, so a client can offer the
    plan that lifts the bound: the lever, the org's plan, the bound, and the
    first plan above it that admits one more (null when none does).
    """
    lever: Annotated[str, Field(title='Lever')]
    limit: Annotated[int | None, Field(title='Limit')]
    plan: Annotated[str, Field(title='Plan')]
    suggested_plan: Annotated[str | None, Field(title='Suggested Plan')]


class PlanLimitsView(BaseModel):
    """
    A plan's bounds; a null count is no bound.
    """
    active_tasks: Annotated[int | None, Field(title='Active Tasks')]
    api_keys: Annotated[bool, Field(title='Api Keys')]
    members: Annotated[int | None, Field(title='Members')]
    storage_bytes: Annotated[int, Field(title='Storage Bytes')]


class PlanOfferView(BaseModel):
    """
    One plan on offer: its bounds and its monthly price. A per-seat plan's
    `flat_cents` covers up to `included_seats` seats, and past them every
    seat is `per_seat_cents`.
    """
    flat_cents: Annotated[int, Field(title='Flat Cents')]
    included_seats: Annotated[int | None, Field(title='Included Seats')]
    limits: PlanLimitsView
    per_seat_cents: Annotated[int, Field(title='Per Seat Cents')]
    plan: Plan


class PlatformSizeView(BaseModel):
    """
    How big the platform is, what the first responder to an alarm reads
    before it escalates: live tenants and users, and the tasks created and
    events produced in the last twenty-four hours, a window that starts at
    `since` and ends at the read.
    """
    events_last_24h: Annotated[int, Field(title='Events Last 24H')]
    since: Annotated[AwareDatetime, Field(title='Since')]
    tasks_last_24h: Annotated[int, Field(title='Tasks Last 24H')]
    tenants: Annotated[int, Field(title='Tenants')]
    users: Annotated[int, Field(title='Users')]


class PurposeUsageView(BaseModel):
    count: Annotated[int, Field(title='Count')]
    pending_count: Annotated[int, Field(title='Pending Count')]
    pending_size_bytes: Annotated[int, Field(title='Pending Size Bytes')]
    purpose: FilePurpose
    size_bytes: Annotated[int, Field(title='Size Bytes')]


class RedirectView(BaseModel):
    """
    Where the person goes next: the processor's hosted page.
    """
    url: Annotated[str, Field(title='Url')]


class RestoreTaskRequest(BaseModel):
    """
    Takes an archived task back to the done list. `expected_version` is the
    task's as the caller read it: 412 `precondition_failed` when it changed
    since, and 422 `validation_failed` when the request names none or the
    task is not archived.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    expected_version: Annotated[ExpectedVersion | None, Field(title='Expected Version')] = None


class Role(StrEnum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'
    viewer = 'viewer'
    service = 'service'


class RowErrorView(BaseModel):
    """
    A row the import skipped: its number, the first data row being 1, and why.
    """
    reason: Annotated[str, Field(title='Reason')]
    row: Annotated[int, Field(title='Row')]


class SecondFactorRequest(BaseModel):
    """
    The code from an authenticator, presented with a sign-in credential.
    The answer is a new sign-in that records the verified code, which the
    operator plane asks of an enrolled operator. A code used once is
    refused.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    totp_code: Annotated[str, Field(max_length=6, min_length=6, title='Totp Code')]


class SessionView(BaseModel):
    """
    Only the hash of a token is ever kept, so a session view carries no secret.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    credential_kind: CredentialKind
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class InvitationToken(RootModel[str]):
    root: Annotated[str, Field(max_length=500, title='Invitation Token')]


class SignInCallbackRequest(BaseModel):
    """
    The code the browser brought back to the callback, and the verifier
    the sign-in's start answered with, which the API exchanges with the
    identity provider, server-side. The answer is a
    sign-in's (`IssuedLoginView`); a person nobody knew is signed up by it,
    with their personal org.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[str, Field(max_length=500, min_length=1, title='Code')]
    code_verifier: Annotated[str, Field(max_length=128, min_length=43, title='Code Verifier')]
    invitation_token: Annotated[InvitationToken | None, Field(title='Invitation Token')] = None


class SignInStartRequest(BaseModel):
    """
    The start of a sign-in at the identity provider. `redirect_uri` is where
    the browser comes back with a code: this environment's portal callback,
    and nothing else. `state` is the caller's own random value, kept by the
    tab that started the sign-in and compared when the browser comes back,
    which binds the round trip to that tab; it may carry nothing else.
    `invitation_token` is the one an invitation's link carried, and
    `sign_up` opens the provider on its sign-up screen.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    invitation_token: Annotated[InvitationToken | None, Field(title='Invitation Token')] = None
    redirect_uri: Annotated[str, Field(max_length=2000, min_length=1, title='Redirect Uri')]
    sign_up: Annotated[bool | None, Field(title='Sign Up')] = False
    state: Annotated[str, Field(max_length=200, min_length=16, title='State')]


class SignInStartView(BaseModel):
    """
    Where the browser goes next, the identity provider's sign-in, and the
    PKCE verifier the tab keeps beside its state and sends back with the
    code. The provider holds only the verifier's digest, so a code is worth
    nothing to anyone who does not hold it.
    """
    authorization_url: Annotated[str, Field(title='Authorization Url')]
    code_verifier: Annotated[str, Field(title='Code Verifier')]


class SignedOutView(BaseModel):
    """
    The credential that ended, a session, a sign-in, or an operator
    token, and `provider_logout_url`: where the browser goes next to end the
    identity provider's session behind it, so the next sign-in on this
    browser asks who it is. Null when the sign-in left no session there
    (the device sign-in, the local sign-in, an operator token). It names the
    provider's session, which is not a secret.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    credential_kind: CredentialKind
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    provider_logout_url: Annotated[str | None, Field(title='Provider Logout Url')] = None
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class SkipReason(StrEnum):
    """
    Why a bulk change left one task alone. Every reason is a fact about the
    task as the change found it, never a failure of the change.
    """
    not_found = 'not_found'
    already_done = 'already_done'
    already_open = 'already_open'
    changed = 'changed'
    plan_limit = 'plan_limit'


class SkippedTaskView(BaseModel):
    """
    A task the bulk change left alone, and why: `not_found`,
    `already_done`, `already_open`, `changed`, or `plan_limit`.
    """
    id: Annotated[UUID, Field(title='Id')]
    reason: SkipReason


class SlackEventAnswerView(BaseModel):
    """
    Slack's check of the events URL gets its `challenge` back; every other
    event is acknowledged with nothing.
    """
    challenge: Annotated[str | None, Field(title='Challenge')] = None


class SlackInstallStartView(BaseModel):
    """
    Slack's own page, where a person approves the install for their
    workspace. The link carries a one-time state, works once, until
    `expires_at`, and is shown here only: a replay under the same
    Idempotency-Key answers with `url` null, and the caller asks for another.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    url: Annotated[str | None, Field(title='Url')]


class SlackInstallationStatus(StrEnum):
    ok = 'ok'
    broken = 'broken'


class SlackInstallationView(BaseModel):
    """
    The Slack workspace the org installed Tadas into, and the channel it
    posts to. `channel_id` is null until someone types `/tadas connect` in a
    channel. `status` is `broken` when Slack refused for good (`broken_reason`
    says which refusal): the channel is gone or the app is not in it, which a
    new `/tadas connect` mends, or the token no longer renews, which a new
    install mends. `created_by` is the member who installed it. The bot token
    is never on the wire.
    """
    broken_reason: Annotated[str | None, Field(title='Broken Reason')]
    channel_id: Annotated[str | None, Field(title='Channel Id')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    id: Annotated[UUID, Field(title='Id')]
    status: SlackInstallationStatus
    team_id: Annotated[str, Field(title='Team Id')]
    team_name: Annotated[str, Field(title='Team Name')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]


class SlackStatusView(BaseModel):
    """
    Whether the org has installed Tadas in Slack, and where.
    """
    installation: SlackInstallationView | None


class Intent(StrEnum):
    sso = 'sso'
    domain_verification = 'domain_verification'


class SsoLinkRequest(BaseModel):
    """
    What the identity provider's admin portal opens on: the single sign-on
    connection (`sso`) or the org's domains (`domain_verification`), and the
    page of this environment's portal it links back to.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    intent: Annotated[Intent, Field(title='Intent')]
    return_url: Annotated[str, Field(max_length=2000, min_length=1, title='Return Url')]


class SsoLinkView(BaseModel):
    """
    A short-lived link to the admin portal; open it at once.
    """
    url: Annotated[str, Field(title='Url')]


class StartCheckoutRequest(BaseModel):
    """
    `return_url` is the portal page the person comes back to, paid or not;
    it is one of the portal's own origins, or the request is refused.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    plan: Plan
    return_url: Annotated[str, Field(max_length=2000, min_length=1, title='Return Url')]


class StartImportRequest(BaseModel):
    """
    The import of a CSV file uploaded under the `task_import` purpose
    (`POST /v1/tasks/imports/files`, then the media routes) and confirmed.
    Its columns are `title` (needed), `notes`, `due_on` (`YYYY-MM-DD`), and
    `assignee_email` (a member of the org), by header name.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    file_id: Annotated[UUID, Field(title='File Id')]


class StorageUsageView(BaseModel):
    """
    What the org keeps in the store, counted from its files: the stored ones
    per purpose and in total, and the uploads started and not yet confirmed.
    A removed file stops counting at once.
    """
    pending_size_bytes: Annotated[int, Field(title='Pending Size Bytes')]
    purposes: Annotated[list[PurposeUsageView], Field(title='Purposes')]
    total_count: Annotated[int, Field(title='Total Count')]
    total_size_bytes: Annotated[int, Field(title='Total Size Bytes')]


class StreamTruncatedDetail(BaseModel):
    """
    What a `stream_truncated` refusal carries: the floor, the highest seq
    trimmed from the stream, and the head. A client drops its cursor, reads
    afresh what it shows, and goes on from the head.
    """
    floor: Annotated[int, Field(title='Floor')]
    head: Annotated[int, Field(title='Head')]


class SubscriptionStatus(StrEnum):
    """
    The processor's statuses, as it spells them.
    """
    incomplete = 'incomplete'
    incomplete_expired = 'incomplete_expired'
    trialing = 'trialing'
    active = 'active'
    past_due = 'past_due'
    canceled = 'canceled'
    unpaid = 'unpaid'
    paused = 'paused'


class TaskScope(StrEnum):
    """
    Which tasks a list shows. The org is the team.
    """
    mine = 'mine'
    team = 'team'


class TaskStatus(StrEnum):
    open = 'open'
    done = 'done'


class TaskView(BaseModel):
    archived_at: Annotated[AwareDatetime | None, Field(title='Archived At')] = None
    assignee_id: Annotated[UUID | None, Field(title='Assignee Id')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')]
    due_on: Annotated[date | None, Field(title='Due On')] = None
    id: Annotated[UUID, Field(title='Id')]
    notes: Annotated[str, Field(title='Notes')]
    position: Annotated[float, Field(deprecated=True, description='The rank as a float, for a client of the release before; order by `rank`. It leaves the wire in the release after this one.', title='Position')]
    rank: Annotated[str | None, Field(description='Where an open task sits in the open list, which is ascending by rank, then by id. An exact decimal number, written out in full: compare two as numbers, never as floats and never as text. Null only from a build that predates it, which orders by `position`.', title='Rank')] = None
    reminded_at: Annotated[AwareDatetime | None, Field(title='Reminded At')] = None
    status: TaskStatus
    title: Annotated[str, Field(title='Title')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    version: Annotated[int, Field(title='Version')]


class TotpConfirmedView(BaseModel):
    """
    The second factor is enrolled: from now on the operator plane admits
    this identity only on a sign-in that verified a code, so the next
    request signs in again with one.
    """
    confirmed_at: Annotated[AwareDatetime, Field(title='Confirmed At')]
    identity_id: Annotated[UUID, Field(title='Identity Id')]


class UpdateIdentityRequest(BaseModel):
    """
    Where the person is, as an IANA name ("Europe/Istanbul"): the portal
    sends the browser's own on sign-in. A due date's reminder goes out at
    nine in the morning in it; with none sent, in UTC. A name that is not
    one is 422.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    time_zone: Annotated[str, Field(max_length=64, min_length=1, title='Time Zone')]


class UpdateMeRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: Annotated[str, Field(max_length=200, min_length=1, title='Display Name')]


class UpdateMembershipRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: Role


class Title(RootModel[str]):
    root: Annotated[str, Field(max_length=500, title='Title')]


class UpdateTaskRequest(BaseModel):
    """
    A partial update: absent fields are kept. An explicit null
    `assignee_id` unassigns the task. The version the update compares with is
    the task's as the caller read it, in the `If-Match` header: the update
    lands only when the task is still at it, and is refused with 412
    `precondition_failed` when another write landed since, so the caller reads
    again and decides over the current task. An update that names no version
    is refused with 422 `validation_failed`, since it would overwrite blind.
    An explicit null `due_on` clears the due date; a new one reschedules the
    reminder, and the one scheduled before it never goes out.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    assignee_id: Annotated[UUID | None, Field(title='Assignee Id')] = None
    due_on: Annotated[date | None, Field(title='Due On')] = None
    notes: Annotated[str | None, Field(title='Notes')] = None
    status: TaskStatus | None = None
    title: Annotated[Title | None, Field(title='Title')] = None


class UploadFieldView(BaseModel):
    name: Annotated[str, Field(title='Name')]
    value: Annotated[str, Field(title='Value')]


class UserView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    display_name: Annotated[str, Field(title='Display Name')]
    email: Annotated[str, Field(title='Email')]
    id: Annotated[UUID, Field(title='Id')]


class ValidationError(BaseModel):
    ctx: Annotated[dict[str, Any] | None, Field(title='Context')] = None
    input: Annotated[Any | None, Field(title='Input')] = None
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]


class WorkKind(StrEnum):
    NOOP = 'NOOP'
    SYNC_SEATS = 'SYNC_SEATS'
    TASK_REMINDER = 'TASK_REMINDER'
    SLACK_POST = 'SLACK_POST'
    ORCHESTRATION = 'ORCHESTRATION'
    WAKE_PARKED = 'WAKE_PARKED'
    DELETE_ACCOUNT = 'DELETE_ACCOUNT'
    UNASSIGN_TASKS = 'UNASSIGN_TASKS'
    DELETE_ORG = 'DELETE_ORG'


class WorkStatus(StrEnum):
    queued = 'queued'
    claimed = 'claimed'
    done = 'done'
    failed = 'failed'


class AddApiKeyRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    role: Role
    ttl_days: Annotated[TtlDays | None, Field(title='Ttl Days')] = None


class AddMemberRequest(BaseModel):
    """
    A person in the org, as `add-member` seeds one; the owner and the
    service role are refused, since the one owner is the one the create
    minted.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: Annotated[str, Field(max_length=200, min_length=1, title='Display Name')]
    email: Annotated[str, Field(min_length=1, title='Email')]
    role: Role


class ApiKeyView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    role: Role
    user_id: Annotated[UUID, Field(title='User Id')]


class BillingView(BaseModel):
    """
    The org's plan now, where it comes from, and what the org uses of it.
    `ends_at` is set when a paid plan is set to end; the org is on
    `plan_after` from then, and keeps everything it has. `can_manage` says
    whether the caller may change the plan: an owner or an admin.
    """
    active_tasks: Annotated[int, Field(title='Active Tasks')]
    can_manage: Annotated[bool, Field(title='Can Manage')]
    cancel_at_period_end: Annotated[bool, Field(title='Cancel At Period End')]
    comped_plan: Plan | None
    current_period_end: Annotated[AwareDatetime | None, Field(title='Current Period End')]
    ends_at: Annotated[AwareDatetime | None, Field(title='Ends At')]
    limits: PlanLimitsView
    monthly_cents: Annotated[int, Field(title='Monthly Cents')]
    paid_plan: Plan | None
    payment_failed: Annotated[bool, Field(title='Payment Failed')]
    plan: Plan
    plan_after: Plan | None
    plans: Annotated[list[PlanOfferView], Field(title='Plans')]
    seats: Annotated[int, Field(title='Seats')]
    status: SubscriptionStatus | None
    storage_bytes: Annotated[int, Field(title='Storage Bytes')]


class BulkListRequest(BaseModel):
    """
    A whole list, by the scope and the status it shows.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    scope: TaskScope
    status: TaskStatus


class BulkTasksRequest(BaseModel):
    """
    A change to many tasks in one call: `complete` or `reopen`, over the
    tasks named in `ids` (at most 1000) or over every task of one list in
    `all`, never both. `all` reads the list on the server, not the page a
    client loaded: `complete` goes with the open list and `reopen` with the
    done list. Each task is an edit of its own, under the rules a single edit
    applies and fenced on the version the call read: a task that is not the
    org's, already in the status asked for, or changed between the read and
    the write is skipped and named, never a refusal of the rest. A reopen
    puts each task on top of the open list, the last one named on top, up to
    the plan's bound on active tasks. The call runs under an
    `Idempotency-Key`, and a retry of it answers what the first one did.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    action: BulkAction
    all: BulkListRequest | None = None
    ids: Annotated[Ids | None, Field(title='Ids')] = None


class BulkTasksView(BaseModel):
    """
    What a bulk change did. `changed` lists the tasks it wrote, in the order
    it wrote them, and `skipped` the ones it left alone; each lists at most
    1000, and the counts beside them are whole. To undo a change, send the
    other action with `changed` as `ids`. `plan_limit` is set when a reopen
    met the plan's bound on active tasks: the tasks past it are skipped as
    `plan_limit`, and it carries what a `plan_limit_reached` refusal does, so
    a client offers the plan that lifts it. Every changed task is announced
    on the realtime channel as `tasks.task.updated`, as a single edit is.
    """
    action: BulkAction
    changed: Annotated[list[UUID], Field(title='Changed')]
    changed_count: Annotated[int, Field(title='Changed Count')]
    plan_limit: PlanLimitDetail | None = None
    skipped: Annotated[list[SkippedTaskView], Field(title='Skipped')]
    skipped_count: Annotated[int, Field(title='Skipped Count')]


class CompPlanRequest(BaseModel):
    """
    The plan an operator grants without a payment; null, or free, takes
    the grant back.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    plan: Plan | None


class FilePageView(BaseModel):
    """
    One page of files, oldest first. `next_cursor` fetches the next page and
    is null on the last one.
    """
    items: Annotated[list[FileView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class IdentityView(BaseModel):
    """
    The person behind the caller's user. `operator_role` is the allowlist
    entry: null for a person who is not an operator.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    email: Annotated[str, Field(title='Email')]
    id: Annotated[UUID, Field(title='Id')]
    operator_role: OperatorRole | None
    time_zone: Annotated[str | None, Field(title='Time Zone')] = None


class ImportView(BaseModel):
    """
    An import of tasks from a CSV file, read as it runs. `status` is
    `running`, `parked`, `succeeded`, or `failed`. `total` is the file's data
    rows, null until the first step counted them; `cursor` is how many were
    read; `created` the tasks the import made, `skipped` the rows it passed
    over, and `row_errors` the first twenty of those with the reason. A
    `parked` import names its `park_reason`: `plan_limit` is the plan's bound
    on active tasks, lifted by a higher plan (which resumes it) or by tasks
    finished and `POST /v1/tasks/imports/{id}/resume`. A `failed` one names
    its `fail_reason`: `file_too_large`, `too_many_rows`, `not_csv`,
    `no_title_column`, `file_gone`, or `defect`. Every change is pushed as
    `orchestrations.orchestration.updated` on the realtime channel.
    """
    created: Annotated[int, Field(title='Created')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    cursor: Annotated[int, Field(title='Cursor')]
    fail_reason: FailReason | None
    file_id: Annotated[UUID, Field(title='File Id')]
    finished_at: Annotated[AwareDatetime | None, Field(title='Finished At')]
    id: Annotated[UUID, Field(title='Id')]
    park_reason: ParkReason | None
    row_errors: Annotated[list[RowErrorView], Field(title='Row Errors')]
    skipped: Annotated[int, Field(title='Skipped')]
    status: OrchestrationStatus
    total: Annotated[int | None, Field(title='Total')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]


class InvitationView(BaseModel):
    """
    A person asked to join the org. The identity provider sent the email
    with the link; `expires_at` is when the link stops working, after which
    the invitation is sent again or replaced.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    email: Annotated[str, Field(title='Email')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    role: Role
    state: InvitationState


class InviteMemberRequest(BaseModel):
    """
    The address to invite and the role the person gets, at most the
    caller's own.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[str, Field(max_length=320, min_length=3, title='Email')]
    role: Role


class IssuedApiKeyView(BaseModel):
    """
    The key in the clear is present on the first response only: the stored
    outcome of the create carries no secret, so a replay under the same
    Idempotency-Key answers with `key` null and `Idempotent-Replayed: true`. A
    client that lost the first response revokes the key and issues another.
    """
    api_key: ApiKeyView
    key: Annotated[str | None, Field(title='Key')]


class IssuedOperatorTokenView(BaseModel):
    """
    The token in the clear, on this answer only; `id` names it afterwards,
    in the list and the revoke, and is no secret. The mint ends the sign-in
    it was given, so a client that lost this answer signs in again for
    another token and revokes the lost one by its id from the list.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    permission: OperatorRole
    token: Annotated[str | None, Field(title='Token')]


class IssuedSessionView(BaseModel):
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    org: OrgView
    role: Role
    token: Annotated[str, Field(title='Token')]
    user: UserView


class IssuedUploadView(BaseModel):
    """
    A form to post the file with, straight to the store: every field, in
    order, then the file as the last field, named `file`. The signed policy
    holds the post to the file's type and at most its size, until
    `expires_at`. A null `url` means the store cannot take a post: the bytes
    go to `PUT /v1/media/files/{id}/content` instead. Then the upload is
    confirmed.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    fields: Annotated[list[UploadFieldView], Field(title='Fields')]
    url: Annotated[str | None, Field(title='Url')]


class LastOwnerDetail(BaseModel):
    """
    What a `last_owner` refusal carries: every team org the person is the
    last owner of, which they hand on or delete before their account goes.
    """
    orgs: Annotated[list[OwnedOrgRef], Field(title='Orgs')]


class MeView(BaseModel):
    app: Annotated[str, Field(title='App')]
    org: OrgView
    permissions: Annotated[list[Permission], Field(title='Permissions')]
    role: Role
    user: UserView


class MembershipChoiceView(BaseModel):
    org: OrgView
    role: Role
    user: UserView


class MembershipView(BaseModel):
    id: Annotated[UUID, Field(title='Id')]
    role: Role
    teams: Annotated[list[UUID], Field(title='Teams')]
    user_id: Annotated[UUID, Field(title='User Id')]


class MintOperatorTokenRequest(BaseModel):
    """
    One permission, never wider than the caller's entry (`write` implies
    `read`), and a lifetime of at most an hour, an hour when absent.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_in: Annotated[ExpiresIn | None, Field(title='Expires In')] = None
    permission: OperatorRole


class OperatorBillingView(BaseModel):
    """
    One org's plan, as the operator plane reads it.
    """
    comped_plan: Plan | None
    ends_at: Annotated[AwareDatetime | None, Field(title='Ends At')]
    paid_plan: Plan | None
    plan: Plan
    status: SubscriptionStatus | None


class OperatorTokenPageView(BaseModel):
    """
    One page of the caller's live operator tokens, newest first;
    `next_cursor` as on `UserPageView`.
    """
    items: Annotated[list[OperatorTokenView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class OperatorWorkItemView(BaseModel):
    """
    One background job as an operator reads it: what it does and for
    which record, where it stands, and how many of its attempts are spent.
    The payload and the claim stay the worker's.
    """
    attempts: Annotated[int, Field(title='Attempts')]
    available_at: Annotated[AwareDatetime, Field(title='Available At')]
    id: Annotated[UUID, Field(title='Id')]
    kind: WorkKind
    last_error: Annotated[str | None, Field(title='Last Error')]
    max_attempts: Annotated[int, Field(title='Max Attempts')]
    status: WorkStatus
    target_id: Annotated[UUID, Field(title='Target Id')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]


class OrgDeletedView(BaseModel):
    """
    The org is gone for everyone in it: `deleted_at` is when. `session` is
    the owner's new session in their personal org, which replaces the one
    that asked, as a switch's does; null when none could be made, and the
    owner signs in again.
    """
    deleted_at: Annotated[AwareDatetime, Field(title='Deleted At')]
    session: IssuedSessionView | None = None


class OrgPageView(BaseModel):
    """
    One page of every org, by id, for the operator plane; `next_cursor` as
    on `UserPageView`.
    """
    items: Annotated[list[OrgView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class TaskCountView(BaseModel):
    """
    How many tasks one list shows: the open list, or the done list without
    the archived tasks, in the scope asked for.
    """
    count: Annotated[int, Field(title='Count')]
    scope: TaskScope
    status: TaskStatus


class TaskPageView(BaseModel):
    """
    One page of a task list. `next_cursor` fetches the next page of the same
    list, open or done, and is null on the last page. The page size is
    clamped, and a list the clamp cut still says a page follows.
    """
    items: Annotated[list[TaskView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class UserPageView(BaseModel):
    """
    One page of the tenant's members. `next_cursor` fetches the next page
    and is null on the last one, so a client reads every member instead of
    whatever a fixed limit happened to cover.
    """
    items: Annotated[list[UserView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class ApiKeyPageView(BaseModel):
    """
    One page of the api key list, newest first; `next_cursor` as on
    `UserPageView`.
    """
    items: Annotated[list[ApiKeyView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class ErrorBody(BaseModel):
    code: Annotated[str, Field(title='Code')]
    last_owner: LastOwnerDetail | None = None
    message: Annotated[str, Field(title='Message')]
    plan_limit: PlanLimitDetail | None = None
    request_id: Annotated[UUID, Field(title='Request Id')]
    stream: StreamTruncatedDetail | None = None


class ErrorResponse(BaseModel):
    error: ErrorBody


class ImportPageView(BaseModel):
    """
    The org's newest imports, newest first.
    """
    items: Annotated[list[ImportView], Field(title='Items')]


class InvitationPageView(BaseModel):
    """
    One page of the org's pending invitations, newest first; `next_cursor`
    as on `UserPageView`.
    """
    items: Annotated[list[InvitationView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class IssuedLoginView(BaseModel):
    """
    Carries the freshly minted login credential in the clear, once.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    memberships: Annotated[list[MembershipChoiceView], Field(title='Memberships')]
    token: Annotated[str, Field(title='Token')]


class MembershipChoicePageView(BaseModel):
    """
    One page of the signed-in person's places, each the org, the user, and
    the role: the same choice a sign-in answers with. `next_cursor` as on
    `UserPageView`.
    """
    items: Annotated[list[MembershipChoiceView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class MembershipPageView(BaseModel):
    """
    One page of the tenant's memberships, by user id; `next_cursor` as on
    `UserPageView`. A page read with the same limit as a page of users
    covers the same members, so roles pair with members page for page.
    """
    items: Annotated[list[MembershipView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]
