# generated by datamodel-codegen:
#   filename:  openapi.json

from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class TtlDays(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=90, title='Ttl Days')]


class AddTaskRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignee_id: Annotated[UUID | None, Field(title='Assignee Id')] = None
    notes: Annotated[str | None, Field(title='Notes')] = ''
    title: Annotated[str, Field(max_length=500, title='Title')]


class CredentialKind(StrEnum):
    api_key = 'api_key'
    session_token = 'session_token'
    login = 'login'
    socket_ticket = 'socket_ticket'
    internal = 'internal'


class EventView(BaseModel):
    """
    One record of the tenant's append-only stream, paged by `after_seq`.
    `kind` is "<namespace>.<entity>.<action>", or an audit kind; the payload
    stays inside, an event is a record and not a second read path. The rename
    from `entity`/`entity_id`/`action` stayed under `/v1` (ADR 0006).
    """
    actor_id: Annotated[UUID, Field(title='Actor Id')]
    kind: Annotated[str, Field(title='Kind')]
    produced_at: Annotated[AwareDatetime, Field(title='Produced At')]
    seq: Annotated[int, Field(title='Seq')]
    target_id: Annotated[UUID, Field(title='Target Id')]


class ExchangeSessionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    org_id: Annotated[UUID, Field(title='Org Id')]


class IdentityView(BaseModel):
    """
    The person behind the caller's user; never carries the password hash.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    email: Annotated[str, Field(title='Email')]
    id: Annotated[UUID, Field(title='Id')]
    is_operator: Annotated[bool, Field(title='Is Operator')]


class IssuedTicketView(BaseModel):
    """
    Carries the freshly minted socket ticket in the clear, once; redeeming
    it opens the channel and re-checks the credential behind it.
    """
    expires_in_seconds: Annotated[int, Field(title='Expires In Seconds')]
    ticket: Annotated[str, Field(title='Ticket')]


class LoginRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[str, Field(title='Email')]
    password: Annotated[str, Field(title='Password')]


class MoveTaskRequest(BaseModel):
    """
    Places an open task right after `after_id`; null puts it at the top.
    `version` is the moved task's, as on `UpdateTaskRequest`.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    after_id: Annotated[UUID | None, Field(title='After Id')] = None
    version: Annotated[int, Field(ge=1, title='Version')]


class OrgView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')] = None
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    slug: Annotated[str, Field(title='Slug')]


class Permission(StrEnum):
    read = 'read'
    write = 'write'
    manage_members = 'manage_members'
    manage_keys = 'manage_keys'


class Role(StrEnum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'
    viewer = 'viewer'
    service = 'service'


class SessionView(BaseModel):
    """
    Only the hash of a token is ever kept, so a session view carries no secret.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    credential_kind: CredentialKind
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class TaskScope(StrEnum):
    """
    Which tasks a list shows. The org is the team.
    """
    mine = 'mine'
    team = 'team'


class TaskStatus(StrEnum):
    open = 'open'
    done = 'done'


class TaskView(BaseModel):
    assignee_id: Annotated[UUID | None, Field(title='Assignee Id')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')]
    id: Annotated[UUID, Field(title='Id')]
    notes: Annotated[str, Field(title='Notes')]
    position: Annotated[float, Field(title='Position')]
    status: TaskStatus
    title: Annotated[str, Field(title='Title')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    version: Annotated[int, Field(title='Version')]


class UpdateMeRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: Annotated[str, Field(max_length=200, min_length=1, title='Display Name')]


class UpdateMembershipRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: Role


class Title(RootModel[str]):
    root: Annotated[str, Field(max_length=500, title='Title')]


class UpdateTaskRequest(BaseModel):
    """
    A partial update: absent fields are kept. An explicit null
    `assignee_id` unassigns the task. `version` is the task's version as the
    caller read it: the update lands only when the task is still at it, and
    is refused with 409 `version_mismatch` when another write landed since,
    so the caller reads again and decides over the current task.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    assignee_id: Annotated[UUID | None, Field(title='Assignee Id')] = None
    notes: Annotated[str | None, Field(title='Notes')] = None
    status: TaskStatus | None = None
    title: Annotated[Title | None, Field(title='Title')] = None
    version: Annotated[int, Field(ge=1, title='Version')]


class UserView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    display_name: Annotated[str, Field(title='Display Name')]
    email: Annotated[str, Field(title='Email')]
    id: Annotated[UUID, Field(title='Id')]


class ValidationError(BaseModel):
    ctx: Annotated[dict[str, Any] | None, Field(title='Context')] = None
    input: Annotated[Any | None, Field(title='Input')] = None
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]


class AddApiKeyRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    role: Role
    ttl_days: Annotated[TtlDays | None, Field(title='Ttl Days')] = None


class ApiKeyView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    role: Role
    user_id: Annotated[UUID, Field(title='User Id')]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class IssuedApiKeyView(BaseModel):
    """
    The key in the clear is present on the first response only: the stored
    outcome of the create carries no secret, so a replay under the same
    Idempotency-Key answers with `key` null and `Idempotent-Replayed: true`. A
    client that lost the first response revokes the key and issues another.
    """
    api_key: ApiKeyView
    key: Annotated[str | None, Field(title='Key')]


class IssuedSessionView(BaseModel):
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    org: OrgView
    role: Role
    token: Annotated[str, Field(title='Token')]
    user: UserView


class MeView(BaseModel):
    app: Annotated[str, Field(title='App')]
    org: OrgView
    permissions: Annotated[list[Permission], Field(title='Permissions')]
    role: Role
    user: UserView


class MembershipChoiceView(BaseModel):
    org: OrgView
    role: Role
    user: UserView


class MembershipView(BaseModel):
    id: Annotated[UUID, Field(title='Id')]
    role: Role
    teams: Annotated[list[UUID], Field(title='Teams')]
    user_id: Annotated[UUID, Field(title='User Id')]


class TaskPageView(BaseModel):
    """
    One page of a task list. `next_cursor` fetches the next page of the same
    list, open or done, and is null on the last page. The page size is
    clamped, and a list the clamp cut still says a page follows.
    """
    items: Annotated[list[TaskView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class UserPageView(BaseModel):
    """
    One page of the tenant's members. `next_cursor` fetches the next page
    and is null on the last one, so a client reads every member instead of
    whatever a fixed limit happened to cover.
    """
    items: Annotated[list[UserView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class ApiKeyPageView(BaseModel):
    """
    One page of the api key list, newest first; `next_cursor` as on
    `UserPageView`.
    """
    items: Annotated[list[ApiKeyView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class IssuedLoginView(BaseModel):
    """
    Carries the freshly minted login credential in the clear, once.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    memberships: Annotated[list[MembershipChoiceView], Field(title='Memberships')]
    token: Annotated[str, Field(title='Token')]
