"""The facade over the generated schema: the names consumers import. Nothing
outside this package imports `schema` directly, so a regeneration that
renames a generated class is absorbed here."""

from tadas.client.schema import (
    ApiKeyPageView,
    ApiKeyView,
    EventView,
    IssuedApiKeyView,
    IssuedLoginView,
    IssuedSessionView,
    IssuedTicketView,
    MembershipChoicePageView,
    MembershipChoiceView,
    MembershipView,
    MeView,
    OperatorEventView,
    OperatorView,
    OrgKind,
    OrgView,
    Permission,
    PlatformSizeView,
    Role,
    SessionView,
    TaskPageView,
    TaskScope,
    TaskStatus,
    TaskView,
    UserPageView,
    UserView,
)

__all__ = [
    "ApiKeyPageView",
    "ApiKeyView",
    "EventView",
    "IssuedApiKeyView",
    "IssuedLoginView",
    "IssuedSessionView",
    "IssuedTicketView",
    "MeView",
    "MembershipChoicePageView",
    "MembershipChoiceView",
    "MembershipView",
    "OperatorEventView",
    "OperatorView",
    "OrgKind",
    "OrgView",
    "Permission",
    "PlatformSizeView",
    "Role",
    "SessionView",
    "TaskPageView",
    "TaskScope",
    "TaskStatus",
    "TaskView",
    "UserPageView",
    "UserView",
]
