"""The facade over the generated schema: the names consumers import. Nothing
outside this package imports `schema` directly, so a regeneration that
renames a generated class is absorbed here."""

from tadas.client.schema import (
    ApiKeyPageView,
    ApiKeyView,
    EventView,
    FilePageView,
    FilePurpose,
    FileStatus,
    FileView,
    IssuedApiKeyView,
    IssuedDownloadView,
    IssuedLoginView,
    IssuedSessionView,
    IssuedTicketView,
    IssuedUploadView,
    MembershipChoicePageView,
    MembershipChoiceView,
    MembershipView,
    MeView,
    OperatorEventView,
    OperatorView,
    OrgView,
    Permission,
    PlatformSizeView,
    PurposeUsageView,
    Role,
    SessionView,
    StorageUsageView,
    TaskPageView,
    TaskScope,
    TaskStatus,
    TaskView,
    UploadFieldView,
    UserPageView,
    UserView,
)

__all__ = [
    "ApiKeyPageView",
    "ApiKeyView",
    "EventView",
    "FilePageView",
    "FilePurpose",
    "FileStatus",
    "FileView",
    "IssuedApiKeyView",
    "IssuedDownloadView",
    "IssuedLoginView",
    "IssuedSessionView",
    "IssuedTicketView",
    "IssuedUploadView",
    "MeView",
    "MembershipChoicePageView",
    "MembershipChoiceView",
    "MembershipView",
    "OperatorEventView",
    "OperatorView",
    "OrgView",
    "Permission",
    "PlatformSizeView",
    "PurposeUsageView",
    "Role",
    "SessionView",
    "StorageUsageView",
    "TaskPageView",
    "TaskScope",
    "TaskStatus",
    "TaskView",
    "UploadFieldView",
    "UserPageView",
    "UserView",
]
