CREATE INDEX ix_slack_posts_org_id_created_at ON core.slack_posts (org_id, created_at);
CREATE INDEX ix_idempotency_records_org_id_attempt_id ON core.idempotency_records (org_id, attempt_id) WHERE status IS NULL;
CREATE INDEX ix_idempotency_records_org_id_created_at ON core.idempotency_records (org_id, created_at);
CREATE INDEX ix_tasks_org_id_deleted_at ON core.tasks (org_id, deleted_at) WHERE deleted_at IS NOT NULL;
DROP INDEX core.ix_orchestrations_status_updated_at;
DROP INDEX core.ix_slack_posts_created_at;
DROP INDEX core.ix_slack_install_states_redeemed_at;
DROP INDEX core.ix_slack_install_states_expires_at;
DROP INDEX core.ix_slack_installations_deleted_at;
DROP INDEX core.ix_billing_deliveries_created_at;
DROP INDEX core.ix_idempotency_records_attempt_id;
DROP INDEX core.ix_idempotency_records_created_at;
DROP INDEX core.ix_invitations_updated_at;
DROP INDEX core.ix_invitations_expires_at;
DROP INDEX core.ix_socket_tickets_expires_at;
DROP INDEX core.ix_sessions_expires_at;
DROP INDEX core.ix_api_keys_expires_at;
DROP INDEX core.ix_api_keys_deleted_at;
DROP INDEX core.ix_memberships_deleted_at;
DROP INDEX core.ix_users_deleted_at;
DROP INDEX core.ix_files_status_created_at;
DROP INDEX core.ix_files_deleted_at;
DROP INDEX core.ix_tasks_deleted_at;
